### ISSUE TITLE
How to import CVE data not coming from NVD (fe. from US-CERT)?

### ISSUE THREAD

**Issue by cudeso** [opencve/opencve#100]
What would be the advise way to add additional data not coming from NVD? US-CERT published advisories on vulnerabilities which are not always included in the NVD feed. For example https://us-cert.cisa.gov/ics/advisories/icsa-21-119-01

Is it possible to "feed" an additional JSON file? How about then creating additional vendors?

**Comment by ncrocfer** [comment]
No OpenCVE doesn't support this feature for the moment, neither create your own vendors outside those provided by NVD db.

**Comment by cudeso** [comment]
OK. I wasn't looking for something directly via the interface but rather creating a file in the same format as the current NVD feed (xml?) and then starting something similar as the current import from NVD but using the locally created file.

**Comment by ncrocfer** [comment]
I close this issue because there is no official supported solution for this use case, please open a PR if needed, we'll be very happy to review & merge it :)
