### ISSUE TITLE
search settings

### ISSUE THREAD

**Issue by rumo20** [opencve/opencve#110]
I have the problem that I have nowhere found settings for the search. On opencve.io the search field says "search in CVEs". In my on premise environment the search field says "Search in CVE description". This means that I cannot search for a CVE number in my on prem installation. Can someone help me here.

**Comment by ncrocfer** [comment]
Opencve.io is based on the last commit, it's not the case of pip install --latest. We'll release a new version in the next days (including tags !), or if you don't want to wait you can also pip install the last commit.

**Comment by rumo20** [comment]
Thank you very much. Go on, its an amazing tool
