### ISSUE TITLE
Search vendor/product with cpe string for fast adding

### ISSUE THREAD

**Issue by dagobertdebug** [opencve/opencve#111]
Hi.

Great tool!

I wonder if it might be possible to search for a CPE string within vendor page, e.g. cpe:2.3:a:postgresql:postgresql:*:*:*:*:*:*:*:*
The use case would be that I have already a list of CPE strings which I want to add for watching.

Thanks, Dago.

**Comment by ncrocfer** [comment]
Duplicates of #92
