### ISSUE TITLE
run `opencve upgrade-db' fail

### ISSUE THREAD

**Issue by wang-qa** [opencve/opencve#113]
**Is your feature request related to a problem?**
If yes please describe it here.

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
If yes please describe it here.

I execute `Initialize the database` Always fail
run `opencve upgrade-db' fail
How do I solve it?

**Additional comment**
Add any other comment here, screenshots or sample code, about your feature request.
![image](https://user-images.githubusercontent.com/58168764/122034135-c9280900-ce03-11eb-9f63-b5acd998307f.png)
![image](https://user-images.githubusercontent.com/58168764/122034402-11dfc200-ce04-11eb-9394-8c7a017a4d91.png)

**Comment by wang-qa** [comment]
I found that I needed to create a user to solve the problem but it was not written in the installation documentation

`create user john with pwaaword 'mysupersecret'`

**Comment by ncrocfer** [comment]
Install postgresql, configure it (including create a user) is of course out of OpenCVE documentation scope ;)
