### ISSUE TITLE
Docker Upgrade Process 

### ISSUE THREAD

**Issue by dagobertdebug** [opencve/opencve#128]
What are the proposed steps in order to upgrade the docker version from e.g. 1.1.0 to 1.2.0?

Is there anything to consider?

Thanks!

**Comment by ldurnez** [comment]
Hello,

There are several steps described inside the release note to help you upgrade:
https://github.com/opencve/opencve-docker/releases/tag/v1.2.0

**Comment by dagobertdebug** [comment]
Many thanks!!
