### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by zerobl0ck** [opencve/opencve#134]
## Expected Behavior
Send email to user after registration/forget password

## Actual Behavior
Do some process and give 502 Bad Gateway nginx error. 

Logs from terminal:
[2021-08-19 08:01:18 -0700] [11576] [CRITICAL] WORKER TIMEOUT (pid:11583)
[2021-08-19 08:01:18 -0700] [11583] [INFO] Worker exiting (pid: 11583)
[2021-08-19 08:01:18 -0700] [11613] [INFO] Booting worker with pid: 11613

Server unable to send email to user's email id.

If I enter wrong in email id in forgot password page, it says "A reset password email has been sent" but if I use correct email id than it gives me error. 

I have configured smtp details in opencve.cfg and I am using sendgrid SMTP service with port 587. I have also used 465.

## Specifications

  - OpenCVE version: opencve, version 1.2.2
  - Python version: Python 3.6.9
  - Platform: Ubuntu 18.04. Manual installation

**Comment by ncrocfer** [comment]
It seems Gunicorn fails:

`[2021-08-19 08:01:18 -0700] [11576] [CRITICAL] WORKER TIMEOUT (pid:11583)`

Can you dump your `opencve.cfg` file here (hiding sensitive data of course) ? You can try to launch the webserver in DEBUG mode.

```
opencve webserver --log-level=DEBUG
```

**Comment by zerobl0ck** [comment]
Sure here is my opencve.cfg:

`[core]
; The name and the port of OpenCVE server. Change it if you launch the
; webserver with a different value (ie opencve webserver -b 0.0.0.0:80).
server_name = <domain name REMOVED>

; Used for securely signing the session cookie, keep it secret !
secret_key = <REMOVED>

; OpenCVE only supports PostgreSQL as database.
database_uri = postgresql://<REMOVED>

; see https://kombu.readthedocs.io/en/latest/userguide/connections.html#connection-urls
celery_broker_url = redis://127.0.0.1:6379/0
celery_result_backend = redis://127.0.0.1:6379/1

; Display the welcome page. If False the user will be
; redirected to the vulnerabilitites (CVE) page.
display_welcome = False

; Display the terms of service page.
display_terms = False

; Number of items to display in tables.
cves_per_page = 20
vendors_per_page = 20
products_per_page = 20
cwes_per_page = 20
reports_per_page = 20
alerts_per_page = 20
tags_per_page = 20
activities_per_page = 20

; Use the werkzeug middleware for reverse proxy
; see https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/
use_reverse_proxy = False

; Display a reCAPTCHA form in register page.
display_recaptcha = False
recaptcha_site_key = sitekey
recaptcha_secret_key = secretkey

[api]
; Enable the API ratelimit
ratelimit_enabled = False

; Default value accross all API routes
; see https://flask-limiter.readthedocs.io/en/stable/#rate-limit-string-notation
ratelimit_value = 3600/hour

; Ratelimit storage URI
; see https://limits.readthedocs.io/en/latest/storage.html
ratelimit_storage_url = redis://127.0.0.1:6379/2

[mail]
; Choices are 'smtp' or 'sendmail'
email_adapter = smtp

; The 'From' field of the sent emails
email_from = <REMOVED>

; Configuration to set up SMTP mails.
smtp_server = smtp.sendgrid.com
smtp_port = 465
smtp_use_tls = True
smtp_username = <REMOVED>
smtp_password = <REMOVED>`

**Comment by zerobl0ck** [comment]
Here is the output of the DEBUG command:

config: None
  bind: ['127.0.0.1:8000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/opencve
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: DEBUG
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: opencve.app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f3c7110ee18>
  on_reload: <function OnReload.on_reload at 0x7f3c7110ef28>
  when_ready: <function WhenReady.when_ready at 0x7f3c711290d0>
  pre_fork: <function Prefork.pre_fork at 0x7f3c711291e0>
  post_fork: <function Postfork.post_fork at 0x7f3c711292f0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f3c71129400>
  worker_int: <function WorkerInt.worker_int at 0x7f3c71129510>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f3c71129620>
  pre_exec: <function PreExec.pre_exec at 0x7f3c71129730>
  pre_request: <function PreRequest.pre_request at 0x7f3c71129840>
  post_request: <function PostRequest.post_request at 0x7f3c711298c8>
  child_exit: <function ChildExit.child_exit at 0x7f3c711299d8>
  worker_exit: <function WorkerExit.worker_exit at 0x7f3c71129ae8>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f3c71129bf8>
  on_exit: <function OnExit.on_exit at 0x7f3c71129d08>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False

**Comment by zerobl0ck** [comment]
My opencve.cfg [file:]

```
[core]
; The name and the port of OpenCVE server. Change it if you launch the
; webserver with a different value (ie opencve webserver -b 0.0.0.0:80).
server_name = (domain name REMOVED)

; Used for securely signing the session cookie, keep it secret !
secret_key = (REMOVED)

; OpenCVE only supports PostgreSQL as database.
database_uri = postgresql://(REMOVED)

; see https://kombu.readthedocs.io/en/latest/userguide/connections.html#connection-urls
celery_broker_url = redis://127.0.0.1:6379/0
celery_result_backend = redis://127.0.0.1:6379/1

; Display the welcome page. If False the user will be
; redirected to the vulnerabilitites (CVE) page.
display_welcome = False

; Display the terms of service page.
display_terms = False

; Number of items to display in tables.
cves_per_page = 20
vendors_per_page = 20
products_per_page = 20
cwes_per_page = 20
reports_per_page = 20
alerts_per_page = 20
tags_per_page = 20
activities_per_page = 20

; Use the werkzeug middleware for reverse proxy
; see https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/
use_reverse_proxy = False

; Display a reCAPTCHA form in register page.
display_recaptcha = False
recaptcha_site_key = sitekey
recaptcha_secret_key = secretkey

[api]
; Enable the API ratelimit
ratelimit_enabled = False

; Default value accross all API routes
; see https://flask-limiter.readthedocs.io/en/stable/#rate-limit-string-notation
ratelimit_value = 3600/hour

; Ratelimit storage URI
; see https://limits.readthedocs.io/en/latest/storage.html
ratelimit_storage_url = redis://127.0.0.1:6379/2

[mail]
; Choices are 'smtp' or 'sendmail'
email_adapter = smtp

; The 'From' field of the sent emails
email_from = (REMOVED)

; Configuration to set up SMTP mails.
smtp_server = smtp.sendgrid.com
smtp_port = 465
smtp_use_tls = True
smtp_username = (REMOVED)
smtp_password = (REMOVED)
```

**Comment by zerobl0ck** [comment]
The issue is resolved.

I was using Ubuntu 18.04 and now I shifted to Ubuntu 20.04. I am not sure what's difference is there but at the end of the day it is resolved and now  I can able to send emails.
