### ISSUE TITLE
Update OpenCVE

### ISSUE THREAD

**Issue by zerobl0ck** [opencve/opencve#135]
How to update OpenCVE?

Is there any command? Or can you provide me doc link so that I can refer that?

I have installed it today but still it is showing old data till 2021-08-18.
So I need to get latest updates. 

Thank you

**Comment by ncrocfer** [comment]
Did you follow the documentation ? https://docs.opencve.io/installation/manual/#start-the-workers

**Comment by ncrocfer** [comment]
No answer from the initial author, I close this issue.
