### ISSUE TITLE
search and filter 

### ISSUE THREAD

**Issue by mostafaimam** [opencve/opencve#144]
I would like to search by the configuration on specific version 
you will find it under cpe_match versionStartIncluding to know how many vulnerabilities in this specific version of the library
how can id o that,

thanks for the amazing job

**Comment by ncrocfer** [comment]
Hi @mostafaimam ,

It's not possible right now. Another similar question was done some months ago, you will find my answer in it: #8

**Comment by ncrocfer** [comment]
Duplicates of #8 (please @mostafaimam use this issue if you want to comment it).
