### ISSUE TITLE
API for product lookup without knowing the vendor ?

### ISSUE THREAD

**Issue by tnemeth** [opencve/opencve#158]
**Is your feature request related to a problem?**
I currently have a list of products with their associated version. In order to lookup for CVEs about these products I have to loop through all the vendors and for each of them, I have to look into their products if the current one I want is among them. Then I
can look at its CVE list.

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
It would be great to have a search_product API that can directly search in all the products in order to speedup products / vendors lookup for accessing their CVE.

**Comment by ncrocfer** [comment]
For me it seems to be a very customize need for you @tnemeth, the current API already allow you to do your job, and this request is very low priority compared to others. So I keep a bit opened your issue, but if nobody ask the same way in the next weeks I will close it (unless you proposed yourself a PR of course ;)).

**Comment by tnemeth** [comment]
Hi !
I did not thought this was really specific :)
In the meantime, I implemented a workaround that is faster.

```shell
password="$1"                                                                                                                                                                           
if [ -z "$1" ]; then                                                                                                                                                                    
        echo "Usage: $0 PGPASSWD"                                                                                                                                                       
        exit 1                                                                                                                                                                          
fi                                                                                                                                                                                      
manifest=~/yocto/manifest                                                                                                                                                               
                                                                                                                                                                                        
sql_opt="-q --csv -p 5432 -h localhost -U opencve -t -d opencve"                                                                                                                        
sql_cmd="select vendors.name from vendors inner join products on vendors.id = products.vendor_id where products.name ="                                                                 
                                                                                                                                                                                        
echo "localhost:5432:opencve:opencve:$password" > ~/.pgpass                                                                                                                             
chmod 600 ~/.pgpass                                                                                                                                                                     
                                                                                                                                                                                        
for package in $(awk '{print $1}' $manifest) ; do                                                                                                                                       
        vendor=$(psql $sql_opt -c "$sql_cmd '$package' ;")                                                                                                                              
        if [ -n "$vendor" ]; then                                                                                                                                                       
                echo "[$package $vendor]"                                                                                                                                               
        fi                                                                                                                                                                              
done                                                                                                                                                                                    
```

**Comment by ncrocfer** [comment]
Ok, I understand, I was tired during my first reading, I didn't understand your request ^^ What you're looking is a simple form (+API) to search about products without knowing the vendor name.

Indeed that's legit and it's not a custom need, everyone can have it :)

Maybe I can add something like the NVD does: https://nvd.nist.gov/products/cpe/search You can directly search into the CPE list. Or a simple text search in the products list (so we abstract the notion of CPE with this feature).

To check.

**Comment by tnemeth** [comment]
Indeed, the CPE search feature could be a great addition. What I like about the results of the NIST CPE search is that products versions are specified in machine-readable format. Not only that but it can be directly linked to the CVEs associated with the specific product version which is what I like about it (in the hope that all previous CVEs have been handled).

**Comment by dogasantos** [comment]
This feature would be great!

**Comment by greengeek** [comment]
I love this option in the GUI.  Can this option please be available also in the API v2?  A lot of the Nmap scans only contain the product name,  for example:

`22/tcp   open  ssh     OpenSSH 8.2p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)`

I can easily parse that for automation, but cannot use it with the OpenCVE API without knowing that the vendor is Openbsd, which Nmap and a lot of other tools don't always provide.
