### ISSUE TITLE
Please support the analysis of vulnerabilities by setting a time period, for example, the number of serious, high-risk and medium risk

### ISSUE THREAD

**Issue by hktalent** [opencve/opencve#159]
Please support the analysis of vulnerabilities by setting a time period, for example, the number of serious, high-risk and medium risk

like
https://www.cvedetails.com/browse-by-date.php
https://www.cvedetails.com/vulnerability-list/year-2021/month-11/November.html

However, it does not support setting the start date and end date for analysis

**Comment by hktalent** [comment]
@ncrocfer  Join me in the development group and control group. I take time to complete this requirement

**Comment by ncrocfer** [comment]
No *development group* and *control group* exists, you can start when you want.
