### ISSUE TITLE
Problems with celery acknowledging configuration

### ISSUE THREAD

**Issue by adc17** [opencve/opencve#170]
I am having an issue with celery not finding the configuration. I'm not sure if I'm getting enough information in the logs to fix it myself and wanted to get some more eyes on this. I am getting the error message within my logs AFTER I have already initialized, upgraded the database, imported data, ran the redis server, and webserver. Both the celery beat and worker are set up as services. Their starting commands are: 

- opencve celery worker -l DEBUG -f /var/log/opencve-worker.log
- opencve celery beat -l DEBUG -f /var/log/opencve-beat.log

Celery beat:
```
Jan 19 02:12:29 ... systemd[1]: Started OpenCVE Celery Beat.
Jan 19 02:12:30 ... opencve[138098]: [error] Configuration not found (use the 'init' command)
Jan 19 02:12:30 ... systemd[1]: opencve-celery-beat.service: Control process exited, code=exited status=1
Jan 19 02:12:30 ... systemd[1]: opencve-celery-beat.service: Failed with result 'exit-code'.
Jan 19 02:12:35 ... systemd[1]: opencve-celery-beat.service: Service RestartSec=5s expired, scheduling restart.
Jan 19 02:12:35 ... systemd[1]: opencve-celery-beat.service: Scheduled restart job, restart counter is at 6781.
Jan 19 02:12:35 ... systemd[1]: Stopped OpenCVE Celery Beat.
```
Celery worker
```
Jan 19 02:12:18 ... systemd[1]: Started OpenCVE Celery Worker.
Jan 19 02:12:18 ... opencve[138064]: [error] Configuration not found (use the 'init' command)
Jan 19 02:12:18 ... systemd[1]: opencve-celery-worker.service: Control process exited, code=exited status=1
Jan 19 02:12:18 ... systemd[1]: opencve-celery-worker.service: Failed with result 'exit-code'.
Jan 19 02:12:23 ... systemd[1]: opencve-celery-worker.service: Service RestartSec=5s expired, scheduling restart.
Jan 19 02:12:23 ... systemd[1]: opencve-celery-worker.service: Scheduled restart job, restart counter is at 6779.
Jan 19 02:12:23 ... systemd[1]: Stopped OpenCVE Celery Worker.
```

I just want to know how to get celery to work properly.

## Specifications

  - OpenCVE version: 1.2.3
  - Python version: 3.8
  - Platform: CentOS 8.4

**Comment by ncrocfer** [comment]
The message is pretty clear: `[error] Configuration not found`, it means OpenCVE doesn't find the `opencve.cfg` file:

https://github.com/opencve/opencve/blob/749f476927e498e899acda6aec05b41e437babd7/opencve/commands/__init__.py#L36

By default `~/opencve.cfg` (generated by the **init** command). You can can change it with the `OPENCVE_CONFIG` variable:
https://github.com/opencve/opencve/blob/749f476927e498e899acda6aec05b41e437babd7/opencve/configuration.py#L9

**Comment by adc17** [comment]
Oh! The default when I install and run 'init' is ~/opencve/opencve.cfg. I'll move the file and see what happens.

**Comment by adc17** [comment]
I moved my config file to my home directory and celery still has issue with finding the configuration file.

**Comment by ncrocfer** [comment]
> Oh! The default when I install and run `opencve init` is `~/opencve/opencve.cfg`. I'll move the file and see what happens.

No my bad, I wrote too quickly, the good location is what you said `~/opencve/opencve.cfg`! So I don't know what is your problem (why OpenCVE doesn't find your config file?).

This is weird because if the `webserver` or any other opencve commands find it so all commands find it, including the Celery related ones.

Do you have a custom configuration? Is-it the same machine where you run `opencve init|webserver` and `opencve celery worker|beat`?

**Comment by adc17** [comment]
I have an ansible role setup to run everything. The only changes I've made are related to settings in the configuration files (redis.conf, opencve.cfg, etc.). Everything is run on the same machine.

**Comment by ncrocfer** [comment]
This seems to be a problem in your custom installation, normal installation works fine. If you show your ansible role maybe someone will help you, otherwise we'll not be able to fix it.

**Comment by adc17** [comment]
Figured it out. Redis was not running properly and, therefore, celery was having trouble running seeing as it relies on the Redis server. The output wasn't super helpful but it was down to my custom configuration.

Thanks. @ncrocfer
