### ISSUE TITLE
Question about Upgrade opencve 1.2.3 to 1.3.0

### ISSUE THREAD

**Issue by jackylam2** [opencve/opencve#173]
Nice and very useful new release

However, is there a way upgrade opencve from 1.2.3 to 1.3.0 gracefully ?

I want the first_time notification setting so much without clearing my setting and data included subscribed vendor and event change

Tried to run  upgrade-db command on opencve 1.2.3 but failed

Please help on upgrading opencve

Thank you

**Comment by ncrocfer** [comment]
Hello,
Upgrading OpenCVE is just ùpip install opencve --upgrade` then `opencve upgrade-db`. When you say it failed, what do you mean by failing? Do you have errors?

**Comment by jackylam2** [comment]
Sorry for late reply.

I forgot to mention im using opencve docker. I cannot upgrade the container image even used docker-compose build --no-cache.

I have to do all the step again from pull the git repos, build the docker image and reinstall. However, all the data gone so I want to know why method to upgrade opencve docker gracefully without data lose.

Thank you.

**Comment by ncrocfer** [comment]
You can try the following procedure: https://github.com/opencve/opencve-docker/issues/23#issue-1115139161

But clearly we have to improve our doc to include this upgrade process ;)

**Comment by jackylam2** [comment]
Thank you ncrocfer.

Will try this in the future since i already reinstall opencve XD

BTW, Thank your for create opencve, this help a lot.
