### ISSUE TITLE
No mail sent by sendmail (OpenCVE docker)

### ISSUE THREAD

**Issue by Legwars** [opencve/opencve#176]
## Expected Behavior

I have configured on my machine sendmail with a server relay, sending mail works.

By installing OpenCVE in docker, in the configuration file I indicated the @IP of my relay server and the port and sendmail.

Normally, once the docker is installed, I'm supposed to receive mail alerts from the platform (or even mail when I create an account)

## Actual Behavior

Here is my current configuration :

[mail]
; Choices are 'smtp' or 'sendmail'
email_adapter = 'sendmail'

; The 'From' field of the sent emails
email_from = opencve@xxxxx.com

; Configuration to set up SMTP mails.
smtp_server = **XXX**.**XXX**.**XXX**.**XXX**
smtp_port = **25**
smtp_use_tls = **False**
smtp_username =
smtp_password =

In the current configuration, I do not receive any messages from the OpenCVE platform. Moreover I did a docker exec -it XXXXXXXXXX /bin.bash to then execute the test command mail/sendmail neither command is recognized in any container

In the server logs, it is written that no alert should be sent, but I don't have any logs that confirm that the connection of the mails is possible.

![image](https://user-images.githubusercontent.com/46921467/154069982-8d5351dd-7f03-4a6a-87f8-b5b6f43ba8ca.png)

![image](https://user-images.githubusercontent.com/46921467/154070098-7ac7c6dc-3955-4565-8d8d-38f45a2ea47c.png)

## Steps to Reproduce the Problem

  - docker-compose --log-level DEBUG up webserver celery_worker
  - echo "Test OK" | sendmail -v xxxxx@xxxxx.com
  - echo "Test OK" | mail -v xxxxx@xxxxx.com
  - 

## Specifications

  - OpenCVE version: 1.3.0
  - Python version: 3.8.10
  - Platform: Ubuntu 20.04 LTS

**Comment by ncrocfer** [comment]
I see in the logs that there is no alert to send, so it's normal you don't receive email. Try to reset your password, it will send you an email.

**Comment by Pablo-Araya** [comment]
Same here, I tried what you siad, and I got an internal error.

![imagen](https://user-images.githubusercontent.com/30483543/158040540-e1e73cc0-52c5-47d3-804c-bc91495e7a4a.png)

it says that my conf is wrong, but I have rechecked it 7 times.
![imagen](https://user-images.githubusercontent.com/30483543/158040697-8a194ed5-fddb-4d70-a37e-d2304c3e1ebc.png)

**Comment by Pablo-Araya** [comment]
Solved... sorry due to there is an option to use TLS if you are using gmail SMTP for connection, the port should be 587 (TLS) and not 465 (SSL)

not it's working

**Comment by ncrocfer** [comment]
Ok so I close this issue (no answer from the original author).
