### ISSUE TITLE
Admin menu: Show subscribed users to products and vendors

### ISSUE THREAD

**Issue by gitmopp** [opencve/opencve#182]
**Feature Request**
When I open the user details (/admin/user/details/?id=) I see the subscribed products and vendors.
It would be great to have the same thing when you see the details for products and vendors (/admin/product/details/?id=).
I want to select a product / vendor and see all subscribed users (name and / or email)

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
In the admin.py add "column_details_list" and "column_formatters_detail" to add the information.

**Comment by gitmopp** [comment]
I modified the code to show the users. It is from my point of view not perfect as the names are shown as "<User xyz>", maybe there is a way to remove the the '<User' part.
And still it would be nice to have the emails.
The idea behind is to manually inform all subsribed users in case there is a CVE which is not officially published.

**Comment by ncrocfer** [comment]
Closed by https://github.com/opencve/opencve/pull/181
