### ISSUE TITLE
password authentication failed for user "opencve"

### ISSUE THREAD

**Issue by b4sh1t1** [opencve/opencve#185]
I want change the password and secure opencve, please explain how to do it.. i did complete setup without password..

**Comment by b4sh1t1** [comment]
I did remove the password, and remove the images with portainer... and redownload them again..

i didn't put any password in .env

and in conf i only put default like this:

secret_key =

after import it's work but opencve keep restarting with this error 

```
  File "/app/venv/lib/python3.7/site-packages/flask_user/token_manager.py", line 43, in __init__
    raise ConfigError('Config setting SECRET_KEY is missing.')
flask_user.ConfigError: Config setting SECRET_KEY is missing.
root@cve:/home/opencve-docker# docker exec -it webserver opencve import-data
Error response from daemon: Container 17f7571457d10fe45d1c56f91d034af76ce1c7cac59fbadb61a8a169111beb2c is restarting, wait until the container is running
root@cve:/home/opencve-docker
```

any help with password or without password apprecaite it!

**Comment by ncrocfer** [comment]
Can you be more verbose?

**Comment by b4sh1t1** [comment]
I wonder how to change the logo and the footer please ?

**Comment by ncrocfer** [comment]
You can't, this is not customizable. What's your usecase?

**Comment by b4sh1t1** [comment]
usecase like this site https://cve.reconshell.com/ it's open source guys and we need just to add our sitename and logo, opencve.io will keep ofcourse.

**Comment by ncrocfer** [comment]
This feature is not currently possible in OpenCVE, so I think they directly changed the logo and the footer in the code, and they build the package using the `setup.py` file.

You can do the same, it's easy you can search *python build from setup.py*, but be careful you will need to upgrade it manually.

Unfortunately I will not provide this feature right now, it's not really important and I have other priorities for OpenCVE (the main one is to migrate from Flask to Django).
