### ISSUE TITLE
upgrade dependencies

### ISSUE THREAD

**Issue by kapouik** [opencve/opencve#189]
## Expected Behavior

Having recent dependencies that work with python 3.10 and a virtualenv

## Actual Behavior

For exemple, Flask is needed in version 1.0.2 that was out in 2018. Near 4 years old ...

## Steps to Reproduce the Problem

$ virtualenv opencve
$ source virtualenv opencve/bin/activate
$ pip install opencve
$ opencve/bin/opencve init
See broken result

## Specifications

  - OpenCVE version: 1.3.0 and latest commit too
  - Python version: 3.10
  - Platform: Fedora and a virtualenv

**Comment by ncrocfer** [comment]
I'm currently migrating OpenCVE from Flask to Django. Python 3.10 will be supported. Meanwhile Flask will not support it.
