### ISSUE TITLE
PostgreSQL Session Configuration

### ISSUE THREAD

**Issue by security101** [opencve/opencve#194]
## Expected Behavior
openCVE opens a persistent connection to the backend postgresql database

## Actual Behavior
The openCVE installation opens over 5000 connections per day. We observed over 4 connections per second opened and closed. 

As side effect when logging on to the application the application reports a internal Server Error which might be  caused because the database connection is closed or not timely setup. The log file entry provided when docker-compose logs -f is used shows psycopg2.OperationalError: SSL SYSCALL error: EOF

## Steps to Reproduce the Problem

  - grep usr=<user to connect to the postgresdb>  /var/log/postgres/postgres-log-YYYY-MM-DD.log | grep " connection authorized:" | wc -l 

## Specifications

  - OpenCVE version: 1.3.0
  - Python version: 3.7.13
  - Platform: docker / opencve:1.3.0 image

**Comment by ncrocfer** [comment]
Currently migrating to Django ORM and leave Flask SQLAlchemy.
