### ISSUE TITLE
ModuleNotFoundError: No module named 'markupsafe'

### ISSUE THREAD

**Issue by zerobl0ck** [opencve/opencve#197]
## Expected Behavior
Install Opencve

## Actual Behavior
Unable to install and giving an error:

ModuleNotFoundError: No module named 'markupsafe'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hhbty4z5/Flask-User/

## Specifications

  - OpenCVE version: latest
  - Python version:3.6.9
  - Platform: ubuntu 18.04/etc/lsb-releasescr server

## Screenshots (optional)
![ece](https://user-images.githubusercontent.com/82965755/168288936-35185e59-a06b-4acd-8aa6-3f1e5793dbd4.png)

**Comment by ncrocfer** [comment]
Can you try to upgrade your Python version please?

I just tried with Python 3.8.9 and it works, I think it's because of your 3.6 version (for information this version is EOL since Dec 2021: https://endoflife.date/python).

I will change the doc to indicate it.

**Comment by ncrocfer** [comment]
Closed because of inactivity.
