### ISSUE TITLE
OpenCVE Twitter Account is Suspended

### ISSUE THREAD

**Issue by gitmopp** [opencve/opencve#199]
In the file [https://github.com/opencve/opencve/blob/master/opencve/templates/emails/report_message.html](https://github.com/opencve/opencve/blob/master/opencve/templates/emails/report_message.html) on line 429 you find a link to Twitter.
The Twitter account [https://twitter.com/opencve](https://twitter.com/opencve) is suspended as it violates the Twitter rules.

My suggestion is to remove the link.

**Comment by ncrocfer** [comment]
You're right, we never used this Twitter account. I will check to remove it from the report page.
