### ISSUE TITLE
windows + docker install failed because of EOF.

### ISSUE THREAD

**Issue by eviltik** [opencve/opencve#201]
## Expected Behavior
install process OK

## Actual Behavior
install process KO

## Steps to Reproduce the Problem

  - follow the install doc

## Specifications

  - OpenCVE version: 1.3.0
  - Python version: N/A (see python version in dockers)
  - Platform: WINDOWS 10/11

## Errors

In both `webserver` and `celery_worker` docker logs, you will see this error message, repeated multiple times.
```
exec user process caused: no such file or directory
```

This is due to CRLF vs LF EOF in the file `run.sh`. Converting CRLF to LF before starting install docker commands solve the problem.

2 possibles fix: 
* use LF rather than CRLF in this repo (all files ?)
* add something in the FAQ or in the doc regarding Windows Docker installation

Cheers !

**Comment by llerch** [comment]
I had the same Problem. Converting CRLF to LF also solved the Problem. Thank you!

**Comment by ncrocfer** [comment]
Thanks for the information @llerch. I close this issue as Windows is not officially supported.
