### ISSUE TITLE
400 Bad Request - Docker version

### ISSUE THREAD

**Issue by Jderach** [opencve/opencve#207]
## Expected Behavior

An account validation address in the format **https**://FQDN sent by email

## Actual Behavior

I use OpenCVE behind a nginx reverse proxy. When registering on OpenCVE, the confirmation link sent is of the form: **http**://FQDN:**443** which induces an error 400. Is it possible to change the format of the validation address in order to have https directly?

## Specifications

  - OpenCVE version: v1.3.0
  - Platform: Ubuntu 20.04
  - Docker version: 20.10.12
  - Docker-compose version: 1.25.0

**Comment by Jderach** [comment]
I have another problem with my installation. I didn't receive updates about CVE by mail but i receive mail for password restoration. Have you any ideas about that ?

**Comment by ncrocfer** [comment]
Duplicates of https://github.com/opencve/opencve-docker/issues/26 (for your 2nd question check if your subscriptions raised an alert and also if your notifications settings are not too strict).
