### ISSUE TITLE
Further clarification of what constitues a "Security Monitoring and Alerting Service" for the purposes of the licence.

### ISSUE THREAD

**Issue by spinnman** [opencve/opencve#211]
**Is your feature request related to a problem?**
If yes please describe it here.

Opencve has monitoring and alerting functionality. In order to use it, configuration including set-up of smtp is required. 

This request is for potential separation or further clarification of what the "actual" definition of a "Security Monitoring and Alerting Service" is for the purpose of the licence. Specifically, this section:

`"...do not use the Licensed Work for a Security Monitoring and Alerting Service.  A "Security Monitoring and Alerting Service" is a commercial offering that allows third parties (other than your employees and contractors) to access the functionality of the Licensed Work so that such third parties directly benefit from the security monitoring and alerting features of the Licensed Work.`

Q1. Is this simply a reference to the configurable alerts in the application? 
Q2. Is a company that uses the software simply to make CVE's available to be searched and viewed on-line by customers in breach of the licence, even if the alerting functionality is not enabled?

What makes the licence open to interpretation is that simply making CVE information publicly available using opencve in itself may be considered by some as enabling a security monitoring feature. It may follow then that anyone who opens up viewing and searching CVE data to third parties could be in breach of the licence.

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
If yes please describe it here.

Idea - Make an addition to the licence that states either:

1. Using the code within this github repository to periodically refresh CVE data and then make it available to third parties in a commercial setting constitutes enabling a security monitoring feature for the terms of our licence.

OR

2. For the purposes of the licence we wish to make it clear that "enabling a security monitoring feature" refers to the facility built into the application to provide notifications by email using the smtp configurations from opencve.cfg.

**Additional comment**
Add any other comment here, screenshots or sample code, about your feature request.

If there is any "in between" options, perhaps considerations around opening up the software to third parties under the terms of a licence fee then perhaps contact information or terms could be added into the available pages in github or via opencve.io.

**Comment by ncrocfer** [comment]
> Q1. Is this simply a reference to the configurable alerts in the application?

No, it concers all the OpenCVE application, not only a "reference to the configurable alerts in the application"

> Q2. Is a company that uses the software simply to make CVE's available to be searched and viewed on-line by customers in breach of the licence, even if the alerting functionality is not enabled?

So referring my previous answer, I confirm this is applicable even if the alerting functionality is not enabled.

To go further we chose the same license as Sentry because we fully agree with their position ([source](https://open.sentry.io/licensing/)):

> We have the following goals regarding our products and services:
>
> - Anyone should be able to run Sentry for themselves or their business.
> - There should be no difference in features between our [SaaS](https://sentry.io/pricing/) and our [self-hosted](https://develop.sentry.dev/self-hosted/) offerings (no open-core model).
> - There should be minimal limitations on usage of code; should be as free as possible.
> - There should be protections from other companies selling our work without giving back.

If you check their LICENSE you will see the similarity with OpenCVE one (https://github.com/getsentry/sentry/blob/master/LICENSE#L12).

**Comment by spinnman** [comment]
Thank you for this clarification. My understanding then is a business can not use opencve if the data is to be shared with a third party in any way. 

Regarding the below:

"There should be protections from other companies selling our work without giving back."

What constitutes giving back? How does a business that wants to use opencve in a way that may benefit clients give back so they can use it? 

Is there any commercial option for example and if so how can that be further explored?

**Comment by ncrocfer** [comment]
No commercial example exist. You can directly [contact me](twitter.com/ncrocfer) to continue this discussion. I close this issue because it's not really related to OpenCVE code itself.
