### ISSUE TITLE
[Bug] Login links not shown on devices with small screen size

### ISSUE THREAD

**Issue by rfuehrer** [opencve/opencve#213]
## Expected Behavior
Login is possible on all devices, provided there is technical support. Devices with small screen widths reduce the content from a smaller width. However, basic functions such as the login procedures are still offered.

## Actual Behavior
The login (link) is not accessible on mobile devices without knowing the login URL, because the "Sign in" and "Register" elements are not displayed.

## Steps to Reproduce the Problem
Calling the start page on a device whose screen or window width is smaller than 767 pixels. The elements are hidden by the CSS as soon as the width is undercut. The behavior is reproducible on all devices, on mobile devices (e.g. iPhone in both portrait and landscape mode) there is only the workaround to call the /login URL manually due to the limited screen size. To reproduce this behavior on desktops, resize the browser window to a smaller size or use the mobile device mode in developer mode/console.

## Possible Steps to Fix the Problem
- remove hidden-xs class in login/register li Elements (line 74/77 in templates/base.html)
- add alternative links for smaller screen sizes (icons?)
- correct .hidden-xs in static/css/bootstrap.min.css or add another @media for smaller sizes

Please feel free to write if the current behavior is intentional. In this case I would refrain from a PR. If support is desired, I am happy to participate with a PR. Instead of the links in the PR, I would either continue to display the text or display an icon instead of the links. Since the registration can also be called via the login page, a single link could actually be used here instead of two links.

## Specifications

  - OpenCVE version: opencve-docker:1.3.0
  - Python version:
  - Platform: Docker

## Screenshots (optional)

The screenshots show that the links for login are not displayed, but the function of login and access to the backend are possible. The pictures were taken on an iPhone 11 Pro.

![SCR-20220819-b9k](https://user-images.githubusercontent.com/25303664/185554041-b5316b1b-f2f6-4bb3-a78d-4b9662eddaf3.png)
![SCR-20220819-b96](https://user-images.githubusercontent.com/25303664/185554050-931c4ad3-2ad7-44d2-8d44-d880c4c8bd87.png)
![SCR-20220819-b8u](https://user-images.githubusercontent.com/25303664/185554052-b21b8962-acff-4c18-be76-13eb4c07d3f4.png)
![SCR-20220819-b8h](https://user-images.githubusercontent.com/25303664/185554057-aac0bdbd-5c42-4b43-aa2f-e92939e63cd6.png)

**Comment by ncrocfer** [comment]
Hi @rfuehrer 

Thank you for reporting this bug :)

Indeed this is not intentional, if you can write a PR I will merge it.

**Comment by rfuehrer** [comment]
Ok, I think the easiest solution is to remove the class from the corresponding li elements. I will provide the changes via a PR

Larger window size:
![image](https://user-images.githubusercontent.com/25303664/185667773-3ea536d0-80e0-478d-8c50-d76600ecc4f3.png)

Smaller window size:
![image](https://user-images.githubusercontent.com/25303664/185667842-87f9e05c-8443-4341-a5a0-1730c8f9af7e.png)
