### ISSUE TITLE
[Feature] Connection/integration to an authentication provider

### ISSUE THREAD

**Issue by rfuehrer** [opencve/opencve#218]
**Is your feature request related to a problem?**

If the solution is to be used in the enterprise corporate sector, it makes sense to connect it to an authentication provider so that existing user accounts can be logged on to the system. With such an integration, the administration of further profile information and account information can be reduced and handled via the provider.

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**

Integration of LDAP/Active Directory via an existing solution such as ldap3 or Flask-LDAP should be considered.

**Additional comment**

none

**Comment by ncrocfer** [comment]
I'm currently working on a refactoring to switch from Django to Flask (because a lot of Flask extensions are unmaintained). Django easily handles this needs, I will add it in next releases.

Closes this because duplicates #104
