### ISSUE TITLE
 How to customize opencve to gatherening vulnerabilities by ours products (Scope)?

### ISSUE THREAD

**Issue by hsninbil** [opencve/opencve#22]
Hello,
I want to customize the opencve to collect the vulnerabilities aligned (/or only dedicated) to my assets (my Information system scope).
Thank you

**Comment by ncrocfer** [comment]
Hello @hsninbil ,

Can you be more precise ? What do you mean by *"collect the vulnerabilities aligned to my assets"* ?

**Comment by hsninbil** [comment]
thank you, i want to customize the opencve configuration to filter as the CVE for the products and applications- CPE- which i set it at the beginning.

**Comment by ncrocfer** [comment]
In OpenCVE you don't directly subscribe to specific CPE, but to `vendors` and `products` linked to CVEs. It's not in the configuration, it's in the UI.

So as a user you just have to collect your assets and click on the `Subscribe` buttons.

**Comment by hsninbil** [comment]
thank you. i will try and give you answer.
