### ISSUE TITLE
select specific version of product for alerting 

### ISSUE THREAD

**Issue by iman4000** [opencve/opencve#226]
Hello and thanks for your great tool :)

The feature that i think is needed is about that you can select only one specific version of product for example i don't want to select apache, i only want to select apache 2.4.33 which it is used in my organization.

i didn't find this feature so i add this request for managing and adding to this amazing tool

**Comment by ncrocfer** [comment]
Hi @iman4000 ,

Thanks for the feedback. Concerning this feature I already answer a long time ago in this issue:

- https://github.com/opencve/opencve/issues/8#issuecomment-754209349

I closed this one because of the duplicate and keep the other opened :)
