### ISSUE TITLE
CWE link error

### ISSUE THREAD

**Issue by Ch-Philou** [opencve/opencve#23]
Hello,

while navigating and testing, i see a small error in cwe link to mitre: in https://www.opencve.io/cwe

Actual:
http://cwe.mitre.org/data/definitions/**CWE-**998.html
Correct:
http://cwe.mitre.org/data/definitions/998.html

Well, i know, that's a not a big issue...

Best regards

**Comment by ncrocfer** [comment]
Hi @Ch-Philou ,

Indeed this is something to fix ! The change will be included in the next release, thank you :)
