### ISSUE TITLE
Dashboard CVE count not in sync with NVD Dashboard count

### ISSUE THREAD

**Issue by theslothuk** [opencve/opencve#233]
## Expected Behavior
Current NVD count at:
https://nvd.nist.gov/general/nvd-dashboard is 196981
OpenCVE count is 196907

## Steps to Reproduce the Problem

  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

**Comment by ncrocfer** [comment]
On OpenCVE:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/1552526/194556245-b5d1fc92-c915-4e77-b44c-ec85e45759e5.png">

On NVD:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/1552526/194556296-68514606-3807-4a44-8ed1-ae7fad391a7e.png">
