### ISSUE TITLE
Web server don't display as it should

### ISSUE THREAD

**Issue by 666Danger-sudo** [opencve/opencve#243]
## Expected Behavior
The web server should run normally with the visual effects.

## Actual Behavior
It only displays the html of the web page as you can see on the screenshot below.

## Steps to Reproduce the Problem
So just follow the exact same steps here: https://docs.opencve.io/installation/manual/
 
## Specifications

  - OpenCVE version: 1.3.0 docker
  - Python version: same as the docker one
  - Platform: My main os is debian but I am trying to implement it with docker-compose

## Screenshots (optional)

![Screenshot from 2022-11-03 12-35-04](https://user-images.githubusercontent.com/46642145/199779930-b1461793-ed9b-4206-b142-6689cef29092.png)

**Comment by mferon** [comment]
Hello,

I already got this issue, it was coming from the `server_name` in `opencve.cfg`.
Your screenshot shows that you use `0.0.0.0:8000` to connect, is it this value in your `opencve.cfg` ?

**Comment by 666Danger-sudo** [comment]
Nope, I leaved the server name on the config file as it was. I will change the value and try again. If its ok, I will close the issue. Thx
