### ISSUE TITLE
Use NVD CVE API instead of "nvdcve-1.1-modified.meta" file

### ISSUE THREAD

**Issue by LukaszC86** [opencve/opencve#249]
**Is your feature request related to a problem?**
Downloading and verifying sha256 value from meta file doesn't work as expected when ISP is caching and refreshing once per ~48h the contents of the meta file. I'm stuck because I've tried two ISPs (main & backup line) and they both cache the contents of the file. 😐

Non-cached example (curl -v -4 https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.meta | cat):
![image](https://user-images.githubusercontent.com/38657823/201654834-1f23053d-68da-45c7-aaa1-6f5018275595.png)

Cached example:
![image](https://user-images.githubusercontent.com/38657823/201655121-680999e5-2c23-4442-a673-669fefd3b397.png)

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
Since the NVD plans to retire the remaining legacy data feeds as well as all 1.0 APIs according to their [change timeline](https://nvd.nist.gov/General/News/change-timeline) in September 2023, it will be required to switch to their [CVE API 2.0](https://nvd.nist.gov/developers/vulnerabilities) anyway. Maybe it could be done sooner?🙂

![image](https://user-images.githubusercontent.com/38657823/201656345-d9e506ae-7939-4e8e-82a5-332d84e85933.png)

**Comment by C0NSTANTINE110** [comment]
same issue
