### ISSUE TITLE
Can I use OpenCVE.io website for commercial purposes?

### ISSUE THREAD

**Issue by MeLebix** [opencve/opencve#250]

**Comment by ncrocfer** [comment]
Can you be more precise?

- if you talk about the tool the answer is **no** (see the [license](https://github.com/opencve/opencve/blob/master/LICENSE)).
- if you talk about the OpenCVE.io website I don't understand the question

**Comment by MichalLebioda** [comment]
Can I use https://www.opencve.io/ website to monitor newest CVE's for apps/programs using in company where I work :D

**Comment by ncrocfer** [comment]
Oh yes, in this case you can of course !
The idea of this project is to help companies on their vulnerabilities alerting :smiley:
