### ISSUE TITLE
Subscriptions activities not displaying on manual install opencve 

### ISSUE THREAD

**Issue by AlexandrePrzy** [opencve/opencve#255]
## Expected Behavior

Subscriptions activities should be displaying like they are on opencve.io .

## Actual Behavior

Subscriptions activities are not being displayed even if I'm using the same filters that I am using on Opencve.io.
Did I forget something in my configuration?

## Steps to Reproduce the Problem

  - Follow manual installations of opencve ( with postgresql installed on windows while opencve is installed on WSL)
  - Subscribe to multiple vendors

## Specifications

  - OpenCVE version: v1.4.0
  - Python version: 3.7.15
  - Platform: Ubuntu 22.04.1 LTS (WSL on Windows 11)

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/100835306/208472651-c7c2f0b3-d84d-475f-8a6e-e4e1cfbc3a52.png)
![image](https://user-images.githubusercontent.com/100835306/208471907-91908ebf-85cf-421d-b684-52c4de63ea64.png)
Here you can see that the subscriptions activities are not being displayed on my local website
![image](https://user-images.githubusercontent.com/100835306/208472035-9ba19b64-bdc8-4155-bfb9-2327272b2b62.png)
![image](https://user-images.githubusercontent.com/100835306/208472475-9eb9a62d-5645-4959-a4a0-94c63e680119.png)
(Worker was on cooldown when I took the picture, that's why the CVE counts are not exactly the same on opencve.io and localhost)
![image](https://user-images.githubusercontent.com/100835306/208473707-c7262b11-73d3-4a70-9f7e-e4c71ca3b7c5.png)
![image](https://user-images.githubusercontent.com/100835306/208473617-0eed3475-b4cb-4901-b163-c82795dfc00f.png)
Though I can't see the subscriptions activites on my local dashboard , I still can find the CVE that has been modified on december 12th shown on opencve.io if I search it in the CVE search tab of my local website

**Comment by ncrocfer** [comment]
When you spawn a local instance of OpenCVE you don't have the history data. That's why you can't see it in your own instance but you can see data in OpenCVE.io :)
