### ISSUE TITLE
Option for users to delete accounts

### ISSUE THREAD

**Issue by ghost** [opencve/opencve#256]
**Is your feature request related to a problem?**
No

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
Yes, please allow users to delete accounts on https://opencve.io portal

**Additional comment**
n/a

**Comment by ncrocfer** [comment]
This feature is unfortunately not supported by the Flask version, but of course it will be the case in the Django one. Waiting that the users who want to remove their account can PM me on [Twitter](https://twitter.com/ncrocfer). That's what I do right now for this need.

**Comment by Mx7ca** [comment]
I don't have a Twitter account. Is there any email address one could write to?

**Comment by ncrocfer** [comment]
Hi @Mx7ca , here is the good place in this case. I just removed your account.

**Comment by johnfearns22** [comment]
I would like to delete one of my [https://opencve.io/](https://opencve.io/) accounts, and don't see functionality for that on the platform. I do not wish to post here publicly the username or any other identifying information about the account. Can you please let me to let me know how to do this?

**Comment by ncrocfer** [comment]
Hi @johnfearns22 ,

I just removed your account, please let me know if everything is ok for you. For the previous requests we used Twitter to talk in PM (or my LinkedIn if you prefer).

Sorry for this bad experience :/ The v2 of OpenCVE is coming very very soon and we'll be clean for this topic.
