### ISSUE TITLE
No Vendors displayed

### ISSUE THREAD

**Issue by stedeluxe** [opencve/opencve#26]
Opencve on premise install in a VM. When viewing the dashboard, CVE's are listed along with vendor tags but clicking the vendor tag does nothing.

When accessing the Vendor tab on sidebar, no vendors are listed and none are displayed when queried from the search function. The Vendors section of the Admin panel is empty.

Running **opencve import-data** again returns:
 _[*] Import already done_

**Comment by ncrocfer** [comment]
Duplicate of #5 ? Check the requirements : https://github.com/opencve/opencve#requirements

**Comment by stedeluxe** [comment]
ok - it was just under 3.5Gb - am now increasing it to 6gb - Is there a way to re-run the import ?

**Comment by ncrocfer** [comment]
Nop, you need to restart the installation from scratch.

**Comment by stedeluxe** [comment]
dropped and rebuilt the db instead of a total app re-install. all looks ok now. thanks Nicholas.
