### ISSUE TITLE
Python package error

### ISSUE THREAD

**Issue by donlino97** [opencve/opencve#262]
## Expected Behavior

Hi
I have a problem while installing opencve ( pip install opencve )
There is a problem in the compatibility of version of  some packages required
## Actual Behavior
There is a problem in the compatibility of version of  some packages required

## Steps to Reproduce the Problem

  - pip install opencve
  - 
  - 

## Specifications

  - OpenCVE version:Last version
  - Python version:Last version
  - Platform: Ubuntu

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/60447121/218710000-a6b7f7de-3716-481e-a0d9-4663c08f406c.jpeg)

**Comment by ncrocfer** [comment]
I didn't try OpenCVE on last Python version, try to use Python 3.7 or 3.8. I **will not** upgrade this current code to support >=3.9 as a lot of dependencies do not support it.

Instead the new OpenCVE 2.0 (based on Django) will support it.

**Comment by donlino97** [comment]
Okay
Thank you

**Comment by firmianay** [comment]
> Instead the new OpenCVE 2.0 (based on Django) will support it.

Great, when will version 2.0 be released?

**Comment by ncrocfer** [comment]
@firmianay As this is a free tool and as I'm not a company working everyday on it I don't have precise roadmap to give you.
