### ISSUE TITLE
NIST NVD shutting down v1.1 API

### ISSUE THREAD

**Issue by infracritical** [opencve/opencve#265]
Sometime in September of this year, NIST will be shutting down its legacy Version 1.1 for API requests.

Here's the URL: https://nvd.nist.gov/vuln/data-feeds

**Comment by ncrocfer** [comment]
I know ;)

**Comment by ncrocfer** [comment]
No ETA to provide you.

**Comment by neditsekulov** [comment]
Regarding shutting down of NIST feeds how are you going to handle the change:
1. Are you going to call NIST version 2.0 API or you are going to reed the feeds from some other source?
2. Are you going to maintain the Flask version of OpenCVE after the Django version is stabilized?

**Comment by ncrocfer** [comment]
@neditsekulov 

1. django version will handle new NVD JSON API + MITRE [repo](https://github.com/cveproject/cvelistv5/)
2. flask version will handle new NVD JSON API for people who can't migrate to the OpenCVE v2, but I will not maintain it. People who want new features will have to migrate to OpenCVE v2

**Comment by agerchev** [comment]
@ncrocfer do you have any time plan for the first release of the django version ?
Do you think it is production ready or there is more left to be polished. 
Is there a chance to be completed before the official deadline of the legacy version of the API ?

**Comment by ncrocfer** [comment]
@agerchev As this project is done on my free time I don't have any ETA to give you.
But be sure it will be ready before the official deadline.

**Comment by ncrocfer** [comment]
For information the ETA has been postponed by the NVD: https://nvd.nist.gov/General/News/change-timeline

> Edit: The retirement timeline has been extended from September to December 15th, 2023.
