### ISSUE TITLE
Celery worker and webserver crashing with: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.naming

### ISSUE THREAD

**Issue by buzz13** [opencve/opencve#267]
## Specifications

  - OpenCVE version: 1.4.0 (Docker)
  - Python version: 3.8
  - Platform: Debian 11

## Full error
ImportError: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.naming' (/app/venv/lib/python3.8/site-packages/sqlalchemy/sql/naming.py)

Followed docker instructions but no luck. celery_worker and webserver crashing with error described.

## env file
OPENCVE_REPOSITORY=https://github.com/opencve/opencve.git
OPENCVE_VERSION=1.4.0
OPENCVE_CONFIG_PATH=./conf/opencve.cfg
OPENCVE_PORT=8100
POSTGRES_USER=opencve

## opencve.cfg
server_name = 0.0.0.0:8100
secret_key = 6cf6g697U8thzt8N
smtp_server = smtp.gmail.com
smtp_port = 465
smtp_use_tls = True
smtp_use_ssl = False
smtp_username =
smtp_password =

Rest untouched. Docker compose file untouched as well.

**Comment by dsteinberg111** [comment]
same by me. Rebuild docker image today and run into that error

**Comment by ShayneSXM** [comment]
Same issue here :
ImportError: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.naming' (/app/venv/lib/python3.8/site-packages/sqlalchemy/sql/naming.py)
Happened on celery_worker, celery_beat and webserver

**Comment by dsteinberg111** [comment]
Build today and error is gone....
Did a 
```sh
docker system prune -a
docker image pull python:3.8-slim-buster
```
before...
So - don´t know the reason - but it works again.

**Comment by ncrocfer** [comment]
This was a bug from alembic: https://github.com/sqlalchemy/alembic/issues/1196

The `1.10.2` release patched this problem, so now it works again: https://github.com/sqlalchemy/alembic/releases/tag/rel_1_10_2

**Comment by ShayneSXM** [comment]
Yeah, it worked for me aswell, thanks a lot !
