### ISSUE TITLE
Cannot install opencve manually either

### ISSUE THREAD

**Issue by buzz13** [opencve/opencve#268]
## Specifications

  - OpenCVE version: 1.4.0
  - Python version: 3.8.10
  - Platform: Ubuntu 20.04.1 LTE

## Warnings and errors
There are several warnings and errors during installation

Collecting opencve
  Downloading opencve-1.4.0-py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.5 MB/s
Collecting nested-lookup==0.2.18
  Downloading nested-lookup-0.2.18.tar.gz (6.9 kB)
Collecting Flask-Migrate==3.0.1
  Downloading Flask_Migrate-3.0.1-py2.py3-none-any.whl (12 kB)
Collecting Flask-Login==0.4.1
  Downloading Flask-Login-0.4.1.tar.gz (14 kB)
Collecting Flask-SQLAlchemy==2.3.2
  Downloading Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl (16 kB)
Collecting Flask-WTF==0.14.3
  Downloading Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting Flask-Assets==0.12
  Downloading Flask-Assets-0.12.tar.gz (22 kB)
Collecting celery==4.3.0
  Downloading celery-4.3.0-py2.py3-none-any.whl (413 kB)
     |████████████████████████████████| 413 kB 24.7 MB/s
Collecting untangle==1.1.1
  Downloading untangle-1.1.1.tar.gz (3.1 kB)
Collecting cpe==1.2.1
  Downloading cpe-1.2.1.tar.gz (2.2 MB)
     |████████████████████████████████| 2.2 MB 48.4 MB/s
Collecting SQLAlchemy-Utils==0.33.11
  Downloading SQLAlchemy-Utils-0.33.11.tar.gz (128 kB)
     |████████████████████████████████| 128 kB 28.7 MB/s
Collecting markupSafe==1.1.1
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux2010_x86_64.whl (32 kB)
Collecting email-validator==1.1.0
  Downloading email_validator-1.1.0-py2.py3-none-any.whl (17 kB)
Collecting SQLAlchemy==1.3.1
  Downloading SQLAlchemy-1.3.1.tar.gz (5.9 MB)
     |████████████████████████████████| 5.9 MB 46.2 MB/s
Collecting importlib-metadata==4.13.0
  Downloading importlib_metadata-4.13.0-py3-none-any.whl (23 kB)
Collecting Flask==1.0.2
  Downloading Flask-1.0.2-py2.py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 10.4 MB/s
Collecting vine==1.3.0
  Downloading vine-1.3.0-py2.py3-none-any.whl (14 kB)
Collecting Flask-Limiter==1.4
  Downloading Flask_Limiter-1.4-py3-none-any.whl (15 kB)
Collecting jinja2==2.11.3
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 28.3 MB/s
Collecting Flask-Gravatar==0.5.0
  Downloading Flask_Gravatar-0.5.0-py2.py3-none-any.whl (7.5 kB)
Collecting psycopg2-binary==2.8.4
  Downloading psycopg2_binary-2.8.4-cp38-cp38-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 37.2 MB/s
Collecting click==7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.4 MB/s
Collecting Flask-Admin==1.5.5
  Downloading Flask_Admin-1.5.5-py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 29.3 MB/s
Collecting Flask-DebugToolbar==0.10.1
  Downloading Flask_DebugToolbar-0.10.1-py2.py3-none-any.whl (326 kB)
     |████████████████████████████████| 326 kB 31.9 MB/s
Collecting cssmin==0.2.0
  Downloading cssmin-0.2.0.tar.gz (3.2 kB)
Collecting werkzeug==1.0.1
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 42.7 MB/s
Collecting itsdangerous==1.1.0
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting requests==2.23.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 6.4 MB/s
### **_Reason for being yanked: none given_**
Collecting Flask-User==1.0.2.2
  Downloading Flask-User-1.0.2.2.tar.gz (74 kB)
     |████████████████████████████████| 74 kB 4.5 MB/s
Collecting arrow==0.13.1
  Downloading arrow-0.13.1-py2.py3-none-any.whl (36 kB)
Collecting Flask-Paginate==0.5.2
  Downloading flask-paginate-0.5.2.tar.gz (5.5 kB)
Collecting Redis==3.3.11
  Downloading redis-3.3.11-py2.py3-none-any.whl (66 kB)
     |████████████████████████████████| 66 kB 1.8 MB/s
Collecting gunicorn==20.0.4
  Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 7.5 MB/s
Collecting deepdiff==4.0.7
  Downloading deepdiff-4.0.7-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 4.5 MB/s
Collecting jsmin==2.2.2
  Downloading jsmin-2.2.2.tar.gz (12 kB)
Collecting Flask-RESTful==0.3.8
  Downloading Flask_RESTful-0.3.8-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from nested-lookup==0.2.18->opencve) (1.14.0)
Collecting alembic>=0.7
  Downloading alembic-1.10.1-py3-none-any.whl (212 kB)
     |████████████████████████████████| 212 kB 47.6 MB/s
Collecting WTForms
  Downloading WTForms-3.0.1-py3-none-any.whl (136 kB)
     |████████████████████████████████| 136 kB 30.6 MB/s
Collecting webassets>=0.11.1
  Downloading webassets-2.0-py3-none-any.whl (142 kB)
     |████████████████████████████████| 142 kB 22.0 MB/s
Collecting kombu<5.0,>=4.4.0
  Downloading kombu-4.6.11-py2.py3-none-any.whl (184 kB)
     |████████████████████████████████| 184 kB 23.5 MB/s
Collecting billiard<4.0,>=3.6.0
  Downloading billiard-3.6.4.0-py3-none-any.whl (89 kB)
     |████████████████████████████████| 89 kB 9.6 MB/s
Collecting pytz>dev
  Downloading pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
     |████████████████████████████████| 499 kB 38.7 MB/s
Collecting dnspython>=1.15.0
  Downloading dnspython-2.3.0-py3-none-any.whl (283 kB)
     |████████████████████████████████| 283 kB 32.4 MB/s
Requirement already satisfied: idna>=2.0.0 in /usr/lib/python3/dist-packages (from email-validator==1.1.0->opencve) (2.8)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata==4.13.0->opencve) (1.0.0)
Collecting limits
  Downloading limits-3.2.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 3.2 MB/s
Requirement already satisfied: Blinker in /usr/lib/python3/dist-packages (from Flask-DebugToolbar==0.10.1->opencve) (1.4)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.23.0->opencve) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.23.0->opencve) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.23.0->opencve) (2019.11.28)
Collecting Flask-Mail>=0.9
  Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 4.3 MB/s
Collecting bcrypt>=2.0
  Downloading bcrypt-4.0.1-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (593 kB)
     |████████████████████████████████| 593 kB 25.6 MB/s
Requirement already satisfied: cryptography>=1.6 in /usr/lib/python3/dist-packages (from Flask-User==1.0.2.2->opencve) (2.8)
Collecting passlib>=1.7
  Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
     |████████████████████████████████| 525 kB 24.4 MB/s
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 38.3 MB/s
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn==20.0.4->opencve) (45.2.0)
Collecting jsonpickle>=1.0
  Downloading jsonpickle-3.0.1-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 6.0 MB/s
Collecting ordered-set>=3.1
  Downloading ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting aniso8601>=0.82
  Downloading aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 1.6 MB/s
Collecting Mako
  Downloading Mako-1.2.4-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 9.1 MB/s
Collecting importlib-resources; python_version < "3.9"
  Downloading importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting typing-extensions>=4
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting amqp<2.7,>=2.6.0
  Downloading amqp-2.6.1-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 5.8 MB/s
Collecting deprecated>=1.2
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting packaging<24,>=21
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.5 MB/s
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.15.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (81 kB)
     |████████████████████████████████| 81 kB 12.0 MB/s
Building wheels for collected packages: nested-lookup, Flask-Login, Flask-Assets, untangle, cpe, SQLAlchemy-Utils, SQLAlchemy, cssmin, Flask-User, Flask-Paginate, jsmin, Flask-Mail
  Building wheel for nested-lookup (setup.py) ... done
  Created wheel for nested-lookup: filename=nested_lookup-0.2.18-py3-none-any.whl size=6881 sha256=1a4ff7e8bd81d3e7dec3009990d96d527d2dec2c71d58fc9e799985914fe83cc
  Stored in directory: /home/jurica/.cache/pip/wheels/49/04/6e/ff9c388873dc950adbc3db1a05b9e9a3fc2680e3db423a6362
  Building wheel for Flask-Login (setup.py) ... done
  Created wheel for Flask-Login: filename=Flask_Login-0.4.1-py2.py3-none-any.whl size=15935 sha256=91d19caa4884e5cf406752baf3658f42ed55234fba86781a1190480bca73db4f
  Stored in directory: /home/jurica/.cache/pip/wheels/ec/8e/42/16110a8b4f17e4ef4bd0abd42969fc1fc38229348de9f071df
  Building wheel for Flask-Assets (setup.py) ... done
  Created wheel for Flask-Assets: filename=Flask_Assets-0.12-py3-none-any.whl size=8471 sha256=1757a9de662e78a85d7fa0fd57f12aa40a4d5bfe8db8dace97fa60bedb4352fc
  Stored in directory: /home/jurica/.cache/pip/wheels/38/be/87/23900db2a32b1826bf3acd92c3d2e019b91cd659e2a8668e42
  Building wheel for untangle (setup.py) ... done
  Created wheel for untangle: filename=untangle-1.1.1-py3-none-any.whl size=3410 sha256=92282cd867127114f44caf11a9cc8f947cb7126bf93fb8daa0e255e7208decfc
  Stored in directory: /home/jurica/.cache/pip/wheels/7f/c5/cc/22e3fc6b9f951bbd4dfdc0ebd1aceb3b9ce4dee7d7780e270a
  Building wheel for cpe (setup.py) ... done
  Created wheel for cpe: filename=cpe-1.2.1-py3-none-any.whl size=77177 sha256=ff48fc7058924763ae0dde44818c66158492a0109c8694b4afe4affed91b6575
  Stored in directory: /home/jurica/.cache/pip/wheels/91/2e/20/b7278a34b31861ace15565acbf90344f0737268f683c4001ce
  Building wheel for SQLAlchemy-Utils (setup.py) ... done
  Created wheel for SQLAlchemy-Utils: filename=SQLAlchemy_Utils-0.33.11-py2.py3-none-any.whl size=89348 sha256=e48c51216c6bcf7b9ad347a97e7e791983978dbe03bfe071ae714a350f5276c9
  Stored in directory: /home/jurica/.cache/pip/wheels/c3/cb/58/5dd1f40d9352e0c62f28120d2a5b0d36def64877e8f16a4493
  Building wheel for SQLAlchemy (setup.py) ... done
  Created wheel for SQLAlchemy: filename=SQLAlchemy-1.3.1-cp38-cp38-linux_x86_64.whl size=1188021 sha256=d728f15ee24f88fbd7c3ee790e6941f03c4b04882b6184cc7e9df17ebd3b5c06
  Stored in directory: /home/jurica/.cache/pip/wheels/05/fe/10/59fa25d20878110064d70d3e3f956b694e693bb66a17f81169
  Building wheel for cssmin (setup.py) ... done
  Created wheel for cssmin: filename=cssmin-0.2.0-py3-none-any.whl size=3788 sha256=0a01eb8cc58f030c0ee0cc66ae1556a4d1b6baee98acb16d822d8e073cb1c97e
  Stored in directory: /home/jurica/.cache/pip/wheels/06/a7/cc/cd30e024f45566de35cb12edaaa09c14c6e81f617e24b65826
  Building wheel for Flask-User (setup.py) ... done
  Created wheel for Flask-User: filename=Flask_User-1.0.2.2-py2.py3-none-any.whl size=130479 sha256=07b0fa7fe29918810a1bbc006ae42f842d7079742ea27762beb3912f7b61319c
  Stored in directory: /home/jurica/.cache/pip/wheels/47/78/33/26881ca332f1eb98b10341efefd5c1e1235942f3d417c5f53b
  Building wheel for Flask-Paginate (setup.py) ... done
  Created wheel for Flask-Paginate: filename=flask_paginate-0.5.2-py3-none-any.whl size=5259 sha256=cca8a5a4027b20b3b980a29decf2daa1634024e103cc61240e0f2d4f8cb885d8
  Stored in directory: /home/jurica/.cache/pip/wheels/ed/a2/39/d1db45a5de1abc1610f64daaff7710e7121ecff735e4995da3
  Building wheel for jsmin (setup.py) ... done
  Created wheel for jsmin: filename=jsmin-2.2.2-py3-none-any.whl size=13918 sha256=c2cd228e3b1f697be291bb7d6cda06dac6a7e5c094d1b5452c73b5b77868ea1a
  Stored in directory: /home/jurica/.cache/pip/wheels/65/b7/04/fc4b059d177fd88f3ca362ad372a15e364b0c5433121c7b135
  Building wheel for Flask-Mail (setup.py) ... done
  Created wheel for Flask-Mail: filename=Flask_Mail-0.9.1-py3-none-any.whl size=7568 sha256=d342771e3bb1390e07e855dda031dbfe69e81c0b3037de82e0019ae4082efcfa
  Stored in directory: /home/jurica/.cache/pip/wheels/98/bc/8c/34c329e4d7efeaf7b9886db0c76d0b23170e54de443f688e3c
Successfully built nested-lookup Flask-Login Flask-Assets untangle cpe SQLAlchemy-Utils SQLAlchemy cssmin Flask-User Flask-Paginate jsmin Flask-Mail
### **_ERROR: importlib-resources 5.12.0 has requirement zipp>=3.1.0; python_version < "3.10", but you'll have zipp 1.0.0 which is incompatible._**
Installing collected packages: nested-lookup, markupSafe, Mako, importlib-metadata, importlib-resources, SQLAlchemy, typing-extensions, alembic, itsdangerous, werkzeug, click, jinja2, Flask, Flask-SQLAlchemy, Flask-Migrate, Flask-Login, WTForms, Flask-WTF, webassets, Flask-Assets, vine, amqp, kombu, billiard, pytz, celery, untangle, cpe, SQLAlchemy-Utils, dnspython, email-validator, wrapt, deprecated, packaging, limits, Flask-Limiter, Flask-Gravatar, psycopg2-binary, Flask-Admin, Flask-DebugToolbar, cssmin, requests, Flask-Mail, bcrypt, passlib, Flask-User, python-dateutil, arrow, Flask-Paginate, Redis, gunicorn, jsonpickle, ordered-set, deepdiff, jsmin, aniso8601, Flask-RESTful, opencve
### **_Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location._**
Successfully installed Flask-1.0.2 Flask-Admin-1.5.5 Flask-Assets-0.12 Flask-DebugToolbar-0.10.1 Flask-Gravatar-0.5.0 Flask-Limiter-1.4 Flask-Login-0.4.1 Flask-Mail-0.9.1 Flask-Migrate-3.0.1 Flask-Paginate-0.5.2 Flask-RESTful-0.3.8 Flask-SQLAlchemy-2.3.2 Flask-User-1.0.2.2 Flask-WTF-0.14.3 Mako-1.2.4 Redis-3.3.11 SQLAlchemy-1.3.1 SQLAlchemy-Utils-0.33.11 WTForms-3.0.1 alembic-1.10.1 amqp-2.6.1 aniso8601-9.0.1 arrow-0.13.1 bcrypt-4.0.1 billiard-3.6.4.0 celery-4.3.0 click-7.1.2 cpe-1.2.1 cssmin-0.2.0 deepdiff-4.0.7 deprecated-1.2.13 dnspython-2.3.0 email-validator-1.1.0 gunicorn-20.0.4 importlib-metadata-4.13.0 importlib-resources-5.12.0 itsdangerous-1.1.0 jinja2-2.11.3 jsmin-2.2.2 jsonpickle-3.0.1 kombu-4.6.11 limits-3.2.0 markupSafe-1.1.1 nested-lookup-0.2.18 opencve-1.4.0 ordered-set-4.1.0 packaging-23.0 passlib-1.7.4 psycopg2-binary-2.8.4 python-dateutil-2.8.2 pytz-2022.7.1 requests-2.23.0 typing-extensions-4.5.0 untangle-1.1.1 vine-1.3.0 webassets-2.0 werkzeug-1.0.1 wrapt-1.15.0

Finally on opencve init same error like in docker 

**_from sqlalchemy.sql.naming import _NONE_NAME as _NONE_NAME
ImportError: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.naming' (/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/naming.py)_**

**Comment by ncrocfer** [comment]
Related to bug in Alembic, already mentionned in this other issue: https://github.com/opencve/opencve/issues/267

But is now fixed on their side.
