### ISSUE TITLE
Missing entries in report details

### ISSUE THREAD

**Issue by Steppenw01f** [opencve/opencve#269]
## Expected Behavior

All vendors displayed in the overview of the reports.html should be listed as tab in the report.html.
All alerts should be displayed in the report detail view.

## Actual Behavior

The amount of vendors proclaimed in the overview are not always displayed in the report detail.
e.g.: 
As seen in the Screenshot 1. five vendors should be listed, but only one is displayed.
But when opening the report details (Screenshot 2.) only Microsoft is displayed.

Additionally to that, the amount of alerts of this report is displayed as 20 (Screenshot 2.), even though in the overview are 566 referenced (Screenshot 2.).

## Steps to Reproduce the Problem

This problem was found in the current "exploring" version on opencve.io.

In order to reproduce the problem I would recommend to look up in the database. The link to the report is [https://www.opencve.io/reports/E1A9NQW9JY56](https://www.opencve.io/reports/E1A9NQW9JY56). 

Otherwise it is possible to check the reports, which have a larger amount of alerts. Here are some more examples:
  - [https://www.opencve.io/reports/8VVC4VX28DHS](https://www.opencve.io/reports/8VVC4VX28DHS) - which is supposed to have 81 alerts and 12 vendors 
  - [https://www.opencve.io/reports/2TQK03KTPZ2M](https://www.opencve.io/reports/2TQK03KTPZ2M) - which is supposed to have 101 alerts and 12 vendors
  - [https://www.opencve.io/reports/1A557SYOUAD0](https://www.opencve.io/reports/1A557SYOUAD0) - which is supposed to have 56 alerts and 12 vendors

## Specifications

Current specification of the opencve on opencve.io

## Screenshots (optional)
1. ![grafik](https://user-images.githubusercontent.com/99090817/224558896-05e19ace-82f9-4968-964a-62a7c1a47a17.png)
2.
 ![grafik](https://user-images.githubusercontent.com/99090817/224558970-9aca55a3-2eb0-4803-987e-1ef55003e677.png)

**Comment by Steppenw01f** [comment]
I would guess, that the cause of this bug is the usage of the pagination in the template, but this is just a guess. 

Keep up the good work :D

Best regards
Steppenw01f

**Comment by ncrocfer** [comment]
This bug was related to the `v1` version and has been fixed in the `v2` one.

Please note no fix will be provided for the `v1` as all development efforts are now focused on v2 ;)
