### ISSUE TITLE
Data Import Schedule & Manual Pull

### ISSUE THREAD

**Issue by stedeluxe** [opencve/opencve#27]
Hi All - What is the update schedule for the Celery workers (I can assume its every 24hrs, but want to check) ?
Also, what time does it run and can this be triggered manually ?

**Comment by ncrocfer** [comment]
Hi,
Sync is done every 15mn. You can not triggered it manually, you need to launch Celery beat (see the README).

**Comment by stedeluxe** [comment]
dropped and rebuilt the db instead of a total app re-install. all looks ok now. thanks Nicholas.
