### ISSUE TITLE
Wanna change the cve_per_page without local database

### ISSUE THREAD

**Issue by RachelWealth** [opencve/opencve#278]
## Expected Behavior
I didn't installopencve in my computer because of huge number of issue while install. But I wanna change the cve_per_page from 20 to 100, is there some method?

## Steps to Reproduce the Problem

  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

**Comment by ncrocfer** [comment]
When installing on your own computer you can use the [cves_per_page](https://docs.opencve.io/settings/#cves_per_page) configuration. On the Saas version you can't, we choose the default value (20).
