### ISSUE TITLE
Unable to install OpenCVE

### ISSUE THREAD

**Issue by thekgromero** [opencve/opencve#281]
## Expected Behavior
Install

## Actual Behavior
Getting requirements to build wheel...error
The licence_file is depreciated

## Steps to Reproduce the Problem

  - Open powershell in user mode
  - pip install opencve
  - 

## Specifications

  - OpenCVE version: latest as of date (16/05/2023)
  - Python version: 3.10.11
  - Platform: Windows

## Screenshots (optional)
![image](https://github.com/opencve/opencve/assets/131699300/9341fa0d-f0b6-4502-be65-db89e0555163)

**Comment by ncrocfer** [comment]
@thekgromero Windows is not supported by OpenCVE, you should try on Linux platform.

**Comment by ncrocfer** [comment]
Windows will not be supported, I close this issue.
