### ISSUE TITLE
Search CPE v2.3 in "Vendors & Product" page on OpenCVE

### ISSUE THREAD

**Issue by mael-actia** [opencve/opencve#287]
I don't know if is normal but I cannot search a CPE v2.3 like "_cpe:2.3:0:debian:debian_linux:11.0:*:*:*:*:*:*:*_" with OpenCVE tools. I can just search keyworks and find in my case the vendor "Debian" and the product "Debian Linux".
I can subscribe on product "Debian Linux", but I receive all CVE of Debian Linux version. However I just want to receive CVE of the version 11 of Debian Linux, like in CPE above.

Somebody can help me, and tell me if it's possible de filter with a CPE in v2.3 format ?

Sincerely

Maël

**Comment by ncrocfer** [comment]
This is not possible with OpenCVE, you can only search/subscribe to vendors or products, not versions or cpes.
