### ISSUE TITLE
Use NVD API instead of JSON data feeds due to deprecation of them in September 2023

### ISSUE THREAD

**Issue by georg2902** [opencve/opencve#291]
I am currently installing opencve locally to research it. To initially import the data the JSON feeds are used. Unfortunately the NVD provides a warning on their website, that the data feeds will be retired in September 2023.

![image](https://github.com/opencve/opencve/assets/17952480/90ea7024-34de-456d-bf9e-c7e994d0ad21)

It is not safe to say, if the feeds will be still available but will not be updated any further or if they will be removed completely. Anyway you have to use the API to retrieve information about CVE changes in the future or the opencve database import/update will probably not be working after September 2023.

**Comment by ncrocfer** [comment]
Duplicates #265
