### ISSUE TITLE
How to update OpenCVE?

### ISSUE THREAD

**Issue by pokix** [opencve/opencve#293]
Hello there!

I'm opening this thread as it may be a dumb question, but I didn't find any mention in the documentation about it. How do I update an existing OpenCVE instance without loosing all my local configuration an subscription?

Thanks in advance for your help

**Comment by ncrocfer** [comment]
Hi @pokix ,

You just have to execute `pip install opencve --upgrade` if you use the manual installation, of follow the process explained here for the Docker installation: https://github.com/opencve/opencve-docker/releases

Sometimes you also have to add new settings in the configuration file, in this case the information is given in the release page: https://github.com/opencve/opencve/releases

**Comment by pokix** [comment]
Hi and thank you for your answer! Yes it works perfectly!
