### ISSUE TITLE
The vendor and products page is empty

### ISSUE THREAD

**Issue by turbo723** [opencve/opencve#296]
## Expected Behavior
 
There should be a list of vendors and products in the "Vendors and Products" page.

## Actual Behavior

The vendor and product page is empty.

## Steps to Reproduce the Problem

  -  I don't see errors in the logs /var/log/messages
  -  I ran the 'opencve import-data' and I get [*] Import already done.
  -  The VM has 8 Gbs of ram and 6 Gbs of ram free.

## Specifications

  - OpenCVE version: Not sure where to look
  - Python version:  3.8.16
  - Platform: Oracle Linux 8.8

## Screenshots (optional)
![Capture](https://github.com/opencve/opencve/assets/26830457/7cfcacd2-5b12-4df0-863f-17aa4b28b42a)

![Capture2](https://github.com/opencve/opencve/assets/26830457/034d615b-f0ce-4ad5-b6e8-970126beab6a)

**Comment by ncrocfer** [comment]
Your vendors&products are empty and you only have 57k CVEs. This is the same issue as this one: https://github.com/opencve/opencve/issues/221

My comment here references other similar issues: https://github.com/opencve/opencve/issues/221#issuecomment-1240282424

**Comment by turbo723** [comment]
Thanks.  I increased the memory but had no luck. I'm not running opencve as docker container.  I did run the opencve import-data --confirm [*] Import already done.

**Comment by ncrocfer** [comment]
You have to flush your database first, then re-execute the import command.

**Comment by turbo723** [comment]
Deleting and creating the database(opencve) populated the Vendor & Products page. Thanks @ncrocfer
