### ISSUE TITLE
Documentation for setting up Redis or Celery

### ISSUE THREAD

**Issue by emi-emi671** [opencve/opencve#297]
I am trying to setting up opencve manually, it seems to be working fine as have a good documentation but daily scheduler to fetching up CVE is not been there as there is no documentation how to set up this. As i have never use Celery and Redis before so it is good to give some hint in the current documentation that how it should need to setup and integrate this.

**Comment by ncrocfer** [comment]
We provide 2 installation mode:

- https://docs.opencve.io/installation/docker/
- https://docs.opencve.io/installation/manual/

The manual installation assumes that you know how to manage dependencies, like Redis or Posgres. If it's not your case I advide you to use the docker based method.

**Comment by emi-emi671** [comment]
Just for the reference if someone still looking this information then follow these instructions:

```
git clone https://github.com/opencve/opencve
cd opencve/
apt install python3-pip postfix redis postgresql
pip3 install -r requirements.txt	
python3 setup.py build
python3 setup.py install

sudo -u postgres psql
create database DBOpenCVE;
create user USEROpenCVE with encrypted password 'PWOpenCVE';
grant all privileges on database opencve to DBOpenCVE;
exit
```

Edit the ~/opencve/opencve.cfg file    according to your needs
```
opencve init
opencve upgrade-db
opencve import-data
opencve create-user admin admin@email.com --admin
```

Create services: 
1) opencve-web.service:
```
[Unit]
Description=openCVE Web service

[Service]
User=root
ExecStart=/usr/bin/python3 /usr/local/bin/gunicorn opencve.app:app

[Install]
WantedBy=multi-user.target
```

2) opencve-worker.service:
```
[Unit]
Description=openCVE worker service

[Service]
User=root
ExecStart=/usr/bin/python3 /usr/local/bin/celery worker -A opencve.app:cel -l INFO

[Install]
WantedBy=multi-user.target
```

3) opencve-beat.service:
```
[Unit]
Description=openCVE beat service

[Service]
User=root
ExecStart=/usr/bin/python3 /usr/local/bin/celery beat -A opencve.app:cel -l INFO

[Install]
WantedBy=multi-user.target
```

and then start running the everything one by one:

run the Redis server first:
`redis-server`

and then the rest:
```
systemctl daemon-reload 
systemctl enable opencve-web
systemctl enable opencve-worker
systemctl enable opencve-beat
systemctl start opencve-web
systemctl start opencve-worker
systemctl start opencve-beat
```


opencve is accessible on 127.0.0.1:8000
