### ISSUE TITLE
Vulnerability update bug

### ISSUE THREAD

**Issue by AymericDAT** [opencve/opencve#303]
## Expected Behavior
Automatic vulnerability updates

## Actual Behavior
The vulnerabilities on my local opencve instance do not update automatically

Is there a way to force the update? Or to update manually? 

## Steps to Reproduce the Problem

opencve is installed in a docker instance
  - 
  - 

## Specifications

  - OpenCVE version: 1.4.1
  - Python version:
  - Platform:

## Screenshots (optional)
<img width="1002" alt="Capture d’écran 2023-08-22 à 18 02 18" src="https://github.com/opencve/opencve/assets/139887966/2c3619e1-19fb-4e3b-81a6-01ba36bbfa72">
<img width="626" alt="Capture d’écran 2023-08-22 à 18 05 12" src="https://github.com/opencve/opencve/assets/139887966/71ae0a3b-b9fa-46f6-98e8-b3049d9d7c7c">

**Comment by AymericDAT** [comment]
<img width="1002" alt="Capture d’écran 2023-08-22 à 18 02 18" src="https://github.com/opencve/opencve/assets/139887966/2c3619e1-19fb-4e3b-81a6-01ba36bbfa72">

**Comment by Jderach** [comment]
When we installed OpenCVE on a new VM to see if the database had been updated, we got the following error:

![MicrosoftTeams-image (32)](https://github.com/opencve/opencve/assets/107416620/e9f824a4-3a12-4e7d-a8f3-eb247dba5162)

Could this be related?

**Comment by ncrocfer** [comment]
Duplicates of:

- https://github.com/opencve/opencve/issues/288
- https://github.com/opencve/opencve/issues/296
- https://github.com/opencve/opencve/issues/299
