### ISSUE TITLE
Error while running command: pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by emi-emi671** [opencve/opencve#309]
`Collecting importlib-metadata==4.13.0 (from -r requirements.txt (line 39))
  Could not find a version that satisfies the requirement importlib-metadata==4.13.0 (from -r requirements.txt (line 39)) (from versions: 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.6.1, 1.7.0, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 3.0.0, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.3.0, 4.3.1, 4.4.0, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.7.0, 4.7.1, 4.8.0, 4.8.1, 4.8.2, 4.8.3)
No matching distribution found for importlib-metadata==4.13.0 (from -r requirements.txt (line 39))`

**Comment by ncrocfer** [comment]
More information will be useful to help you. I close this issue, please recreate a new one using the template.
