### ISSUE TITLE
CVE Alert - Does not issue email about new vulnerability and subscribed vendors.

### ISSUE THREAD

**Issue by 26088304** [opencve/opencve#315]
Dear friend, I want to thank you for your work at OPENCVE. In this regard, we have implemented the Docker version in my office due to its great stability. It really is an excellent application and we are very excited to advance its use. If possible, I need you to tell me why sometimes the installation stops sending ALERTS, since the containers are up, the applications are Ok, the SMTP is operational since the forgotten password does work. But we have observed that suddenly the application stops sending alerts for CVEs linked to Vendors and I need to be able to fix this error. If you can explain to me where to analyze this, I would greatly appreciate it. Thank you.

**Comment by ncrocfer** [comment]
Please give your logs here, it will be easier to help you :)

**Comment by 26088304** [comment]
[Logs.zip](https://github.com/opencve/opencve/files/13281846/Logs.zip)

Good morning dear friend, In the attachment I send you the 5 logs of the containers of my installation. I tell you that this installation has stopped reporting alerts. It was working fine until suddenly on November 3rd it stopped working. This has already happened to me many times, my installation works for 2 months with the associated vendors releasing alerts and suddenly it stops reporting alerts. Forgotten password works so SMTP is not the problem. If you can give us some guidance on what we can do so that the installation sends alerts again, I will appreciate it. Thank you in advance for all your help and I congratulate you for the initiative. Hug.


Fri, 03 Nov 2023 02:02:13 [[63 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/1607be8d-8cd1-4731-a5e9-912e3996e356)]
Thu, 02 Nov 2023 21:02:12 [[16 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/33a211cb-3e30-4157-a81c-8fde1ab9756c)]
Thu, 02 Nov 2023 19:02:11 [[75 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/03f32015-5311-4499-ba98-c7b4f5392762)]
Thu, 02 Nov 2023 17:05:57 [[42 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/b2e76396-a5f5-4d3e-8a87-30fab3ac8237)]
Thu, 02 Nov 2023 02:32:07 [[115 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/b7ed665a-dfa7-4755-b1b0-43690b0818a3)]
Wed, 01 Nov 2023 23:32:06 [[57 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/513fb86c-552b-4b94-acf6-a0eb623774dc)]
Wed, 01 Nov 2023 20:02:06 [[14 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/3d6cdaec-1162-41bc-a931-4d36c876dbdd)]
Wed, 01 Nov 2023 19:02:05 [[55 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/53a45ca9-e321-435c-b774-60f9acc693bf)]
Wed, 01 Nov 2023 17:17:05 [[84 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/b5891cd7-f499-4b4a-a021-0a9774fcc23a)]
Wed, 01 Nov 2023 04:32:02 [[172 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/9c174e97-40f0-4c2d-8248-7bfde16a9461)]
Wed, 01 Nov 2023 01:47:01 [[29 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/aed28724-7cec-4923-a942-6c2386689952)]
Tue, 31 Oct 2023 21:02:00 [[12 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/9a8d777a-b7ef-4f06-a5e0-401fedbd7243)]
Tue, 31 Oct 2023 18:46:59 [[13 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/d64b6aa9-eae7-4981-856a-bbddb29ad71e)]
Tue, 31 Oct 2023 17:01:59 [[40 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/49e0176d-e925-42e0-ad56-122195d6bc26)]
Tue, 31 Oct 2023 15:01:59 [[31 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/d0718d6e-2f93-46c2-b936-4c2f06476b13)]
Tue, 31 Oct 2023 13:01:58 [[85 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/ee935ea7-b0de-4c67-86c6-c7e8b6c56f35)]
Tue, 31 Oct 2023 11:17:02 [[11 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/a10cd0f3-3512-44a7-a01e-c72fa8a78cf3)]
Tue, 31 Oct 2023 09:02:01 [[8 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/2b2e0129-c961-4cf4-aa81-8607caf8613c)]
Tue, 31 Oct 2023 07:01:57 [[32 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/e6d1958c-fca0-4aa5-b26e-3facc97672e3)]
Tue, 31 Oct 2023 02:02:00 [[18 changes](http://alertascve.anses.gov.ar:8080/admin/tasks/0e0a659d-0778-4226-90d9-7747cdb233b9)]

**Comment by 26088304** [comment]
I add one more information. When you REBOOT the server, the pending tasks are updated. I did the test and verified that I now have the tasks up to date, but it never again issues vulnerability alerts according to subscribed vendors. Something happens that causes the application to stop reporting and doing CVE update tasks. When doing the reboot, it does the tasks again but never returns to normal with respect to issuing email to alert of new vulnerabilities. Can you tell me where I can verify everything related to SMTP mailing of CVE alerts? I urgently need to be able to have this service active. The implementation is done by docker and is 100% ok. The installation didn't give me any errors. If you can help us I will thank you. Atte.

**Comment by 26088304** [comment]
I add something else in case you can answer my question at some point. I rebooted the server where opencve is installed and without further ado, the opencve engine reported cve alerts again. I understand that in reboot I help to fix this blocking of sending cve alerts. The question is why the application hangs or blocks by itself??? Maybe it means that I have created 20 different profiles to report. that is, 20 different users with their corresponding associated vendors. Could it be that having 20 work profiles with their linked vendors generate this tool block? Could you please give me some guidance so I can continue evaluating opencve?

I hope for your words, which are the ones that resolve this issue.

thank you

**Comment by ncrocfer** [comment]
Did you at least check your own logs before writing here every day for someone else finding a solution for you?? I just quickly opened the worker ones and I can see the following traceback that can be a good start:

```
[2023-11-03 04:47:14,657: INFO/ForkPoolWorker-4] HANDLE_REPORTS[66eb9898-d5c7-45fe-ba0d-581213ad4e63]: Get the users who want to always receive email...
[2023-11-03 04:47:14,661: INFO/ForkPoolWorker-4] HANDLE_REPORTS[66eb9898-d5c7-45fe-ba0d-581213ad4e63]: Checking 12 users with alerts to send...
[2023-11-03 04:47:14,663: INFO/ForkPoolWorker-4] HANDLE_REPORTS[66eb9898-d5c7-45fe-ba0d-581213ad4e63]: 3 alerts to notify for IntegraciónyAnálisisdeDatos
[2023-11-03 04:47:14,678: INFO/ForkPoolWorker-4] HANDLE_REPORTS[66eb9898-d5c7-45fe-ba0d-581213ad4e63]: Report 14956ebd-173f-4dc1-b5bf-cfef4a4f219b created.
[2023-11-03 04:47:14,704: ERROR/ForkPoolWorker-4] Task HANDLE_REPORTS[66eb9898-d5c7-45fe-ba0d-581213ad4e63] raised unexpected: UnicodeEncodeError('ascii', 'AlertaCVE-IntegraciónyAnálisisdeDatos@****', 19, 20, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/venv/lib/python3.8/site-packages/opencve/tasks/reports.py", line 166, in handle_reports
    user_manager.email_manager.send_user_report(
  File "/app/venv/lib/python3.8/site-packages/opencve/extensions.py", line 64, in send_user_report
    self._render_and_send_email(
  File "/app/venv/lib/python3.8/site-packages/flask_user/email_manager.py", line 191, in _render_and_send_email
    self.user_manager.email_adapter.send_email_message(
  File "/app/venv/lib/python3.8/site-packages/flask_user/email_adapters/smtp_email_adapter.py", line 64, in send_email_message
    self.mail.send(message)
  File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/app/venv/lib/python3.8/site-packages/flask_mail.py", line 121, in sanitize_address
    return formataddr((nm, addr))
  File "/usr/local/lib/python3.8/email/utils.py", line 91, in formataddr
    address.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xf3' in position 19: ordinal not in range(128)
[2023-11-03 04:47:14,705: INFO/MainProcess] Received task: RELEASE_LOCK[e1f48fe5-b2fe-40b2-ac97-16e4567b1329]  
[2023-11-03 04:47:14,710: INFO/ForkPoolWorker-4] Task RELEASE_LOCK[e1f48fe5-b2fe-40b2-ac97-16e4567b1329] succeeded in 0.002975784009322524s: None
```

It seems the `AlertaCVE-IntegraciónyAnálisisdeDatos@******` is not well parsed by the `flask_mail` extension. Apparently it's a [known issue](https://github.com/miguelgrinberg/flasky-first-edition/issues/2), so just change your email adress without non-ascii letters in it.

PS: I hide your domain in my message but please note you disclosed here some information about your company, like url & professional email. It's not recommended to do that in public issues.
