### ISSUE TITLE
NVD Legacy Data Feed

### ISSUE THREAD

**Issue by cunaz** [opencve/opencve#322]
Since i don`t know the best place to post this, ive choosen this way - so  hopefully this is right.

According to the NVD the Json Data feed will go EOL on December 15 2023 - https://nvd.nist.gov/vuln/data-feeds#JSON_FEED

Is this on your radar?

**Comment by ncrocfer** [comment]
Hi,
Yes I'm on it, ETA end of November.

*ps: please next time use the given template instead of deleting it*
