### ISSUE TITLE
Reduce/filter the amount of mails sent.

### ISSUE THREAD

**Issue by debuglevel** [opencve/opencve#342]
**Is your feature request related to a problem?**
I recently started to use OpenCVE but just unsubscribed again. I received just too many mails about some CVEs from 2022 (e.g. "*Changes* : References changed, CWEs changed").

To be honest I just want to be answered the question "Is there a new security issue in my product/version?"

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
Maybe it would be possible to filter to those *Changes*: ..." which indicate that this is something new.

**Comment by ncrocfer** [comment]
This is already possible using the notifications settings, you hust have to select the first 2 options:

<img width="690" alt="image" src="https://github.com/opencve/opencve/assets/1552526/3ea90c25-52df-45d0-8935-7dc83c232954">

**Comment by debuglevel** [comment]
Oh, that's great! No idea how I overlooked this :)
