### ISSUE TITLE
Limitations of the cloud instance

### ISSUE THREAD

**Issue by shnsys** [opencve/opencve#347]
We're currently setting up an on-premises server for OpenCVE. However, now that the cloud instance is available, I'd like to understand its limitations compared to the on-premises server. So far, I've noticed that the on-premises instance offers a separate admin portal, which isn't available in the cloud instance. Besides that, what other limitations should we be aware of? Also, are there any charges associated with the cloud instance, or is it completely free?

**Comment by ncrocfer** [comment]
Today (1st March, 24) OpenCVE is free and you don't have any limitation on the soft. As you said you're not admin of the Saas version so you don't have access to the `/admin` endpoint. That's all.

But this v1 version is limited in features and we worked during the last year to develop **OpenCVE v2**. A lot of things changed, you can have some details here: https://docs.opencve.io/faq/#what-changes-between-opencve-v1-and-v2

In a few weeks we'll upgrade the Saas instance to the v2 version. As a user you will be able to freely use it with some limitations (the number of subscriptions for instance). You will be able to benefit from higher quotas with a simple and low pricing.

Of course **we'll continue to be transparent and to provide the code on Github**. If you want to install it on-premise you will be able to do it, without paying anything. 

The only condition is to **not use it for commercial usage**. If you want to use it for your personal needs, or to protect your own company it's totally ok. But as stipulated [in the license](https://github.com/opencve/opencve/blob/master/LICENSE) you can't resell OpenCVE instance neither use it as a MSSP company to make benefits with it.

**Comment by shnsys** [comment]
Thank you for the explanation :)
