### ISSUE TITLE
OpenCVE website won't send E-Mail Notifications

### ISSUE THREAD

**Issue by exequze** [opencve/opencve#349]
## Expected Behavior

When a CVE is changed or added i expect to get an E-Mail notification.
## Actual Behavior
I dont get any Notification. The E-Mail works (tried with Password reset)

## Steps to Reproduce the Problem

  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform: https://www.opencve.io/welcome

## Screenshots (optional)

**Comment by ncrocfer** [comment]
I don't have any information to answer you, please open an issue with completed fields and reproductible examples ;)

**Comment by exequze** [comment]
What information do you need?
