### ISSUE TITLE
Flows blocked - Data not updating

### ISSUE THREAD

**Issue by Chloe-Bo** [opencve/opencve#350]
Hello, 

I have OpenCVE installed with Docker-compose in Ubuntu.
My Ubuntu is in VM in Cloud with Scaleway. 

For security, I have some rules to block traffic in so I have an error when celery_worker try to update database.
![image](https://github.com/opencve/opencve/assets/122780773/3716f2c6-6b04-48f1-8d63-ff8b6be891cd)

In Scaleway for the moment, is allow : 
![image](https://github.com/opencve/opencve/assets/122780773/1e30efe4-2b37-45a8-9ac8-53b2ebd45076)

Can you help me ? 
Can you give me port or IP address used by Celery ?

Thanks

**Comment by ncrocfer** [comment]
From your logs it seems your OpenCVE worker can't access `nvd.nist.gov`.
Unfortunately this issue is on your side, we can't give you any port or IP address as we don't manage your own infra :)

**Comment by cstromblad** [comment]
That's most definitely a Docker DNS issue. Solve that, and you will have solved your troubles.
