### ISSUE TITLE
use docker install then can not access homepage

### ISSUE THREAD

**Issue by topsekadmin** [opencve/opencve#352]
install setp for blow

![image](https://github.com/opencve/opencve/assets/59950798/c9501af8-634e-494d-a08b-bef601e3340d)
![image](https://github.com/opencve/opencve/assets/59950798/db89019c-d924-4967-9d02-2a0b2a669eb8)
![image](https://github.com/opencve/opencve/assets/59950798/c3c56883-29ab-4bf1-b9eb-0e7f159669cc)

please help ,thank you

**Comment by jusplayin** [comment]
Same thing I am seeing ArchLinux docker-compose, including the bcrypt error when creating users - I also do not see email being send in my case.  When I use lynx to test I get 404.

Came here to see if others were having the issue
