### ISSUE TITLE
Issue with Tagging Fortnite Posts

### ISSUE THREAD

**Issue by jkprob** [opencve/opencve#366]
I am writing to bring to your attention an ongoing issue regarding the tagging of posts related to Fortnite on your platform.
I have noticed that recently, the posts about Fortnite are not tagged with the appropriate product tag, which is "Fortinet." Due to this oversight, I am not receiving real-time notifications about new vulnerabilities associated with Fortnite.

Could you please address this matter promptly? Ensuring that the correct tags are assigned to posts will greatly assist subscribers like myself in staying informed about potential security risks.

Thank you for your attention to this issue.

![obraz](https://github.com/opencve/opencve/assets/166711477/59795ff8-e2ad-4b0d-a597-c2ff71452e6f)
![obraz](https://github.com/opencve/opencve/assets/166711477/848f1246-f13a-4da5-b1be-632c66f913f3)

**Comment by ncrocfer** [comment]
This is not an issue as the NVD is still analyzing this CVE so no CPE has been attached to it:

<img width="1355" alt="image" src="https://github.com/opencve/opencve/assets/1552526/7281f710-d252-4b0e-8cee-1592f057dac0">

See this answer for an explanation: https://github.com/opencve/opencve/issues/345#issuecomment-1960922089
