### ISSUE TITLE
ERROR - During installation of OpenCVE v2

### ISSUE THREAD

**Issue by mael-actia** [opencve/opencve#368]
## Actual Behavior
When I run the ./install.sh script to install OpenCVE, I get an error message. An error on the following containers appeared :
 - airflow-scheduler
 - airflow-worker
 - airflow-webserver

When I come to look at the container logs, I notice the following errors :
`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.4), port 5432 failed: FATAL:  password authentication failed for user "opencve"`

Please note that I have not changed any passwords in the various configuration files. The default passwords are used.

## Steps to Reproduce the Problem

  - ./install add-config-files
  - ./install.sh set-airflow-start-date
  - ./install.sh start-docker-stack

## Specifications

  - OpenCVE version: v2
  - Python version: 3.11
  - Platform: Debian 12

**Comment by mael-actia** [comment]
Thank you for your reply, it helped me solve my problem.

I have a question about the OpenCVE API. How does it work with adding organizations and projects ?

**Comment by ncrocfer** [comment]
Only RO for the moment, RW will come later when OpenCVE v2 will left the beta phase (no precise ETA to give you) :)

I close this issue as the original question is now done ;)

**Comment by davidbeiler1** [comment]
what if im doing it via pip install opencve?
