### ISSUE TITLE
Webhook format in v2

### ISSUE THREAD

**Issue by ZazaKumar** [opencve/opencve#375]
Hello! I'm trying to send a webhook to mattermost server, the format should be {"text": "report text" }

Can I somehow format json on the opencve side? As i see now i can change only headers

**Comment by ncrocfer** [comment]
Hello,

The format used by the webhook notification can't be changed, you have to integrate a middleware used to handle it and reformat it for your need.

**Comment by ZazaKumar** [comment]
okay, thank you!
