### ISSUE TITLE
OpenCVE : No update of the new CVE 

### ISSUE THREAD

**Issue by hsninbil** [opencve/opencve#376]
## Expected Behavior
- web server is working 
- No update of the new CVE
- 
## Actual Behavior

root@lab-virtual-machine:/opt/opencve-docker# docker exec -it webserver opencve import-data
WARNING: Flask-User TokenManager: SECRET_KEY is shorter than 32 bytes.
[*] Import already done.

## Steps to Reproduce the Problem

  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

**Comment by ncrocfer** [comment]
I close this issue as the original author didn't give enought information for us to help him.
