### ISSUE TITLE
Official Helm Chart ?

### ISSUE THREAD

**Issue by tesence** [opencve/opencve#399]
Hello !

I was wondering if there were any plans (potentially for v2) to provide an official helm chart for OpenCVE ?

**Comment by ldurnez** [comment]
Hello @tesence,

Yes, we are planning to release one later on, as we are focusing on the merge of the v2 inside the main branch for now.

**Comment by MoussaOudihat** [comment]
Hello @ldurnez any news about the official helm chart for the v2

**Comment by burnziii** [comment]
Any news regarding the official helm chart?

**Comment by ncrocfer** [comment]
No, we're currently focused on other priorities.

**Comment by ncrocfer** [comment]
@nxenon 

Comments like “No helm chart yet ??” definitely help motivate people to spend their free time building and maintaining one for the community... 🤦‍♂️

As mentioned previously, we’re currently focused on other priorities. Contributions are of course welcome if this is something you’d like to help with.

Also, Kubernetes/Helm is not really our area of expertise, so even if a chart is created, it likely wouldn’t be officially maintained by the OpenCVE team. We’d however be happy to reference and redirect users to a community-maintained repository.

**Comment by ITViking** [comment]
@ncrocfer I'm interested in making a PR for a helm chart as we are missing that feature as well... Would a PR be welcome and are you guys open to answering questions to aid me in figuring out the internals so I can make it? 
We are also open to helping maintaining the helm chart. 
Hit me up if this is of any interest

**Comment by ncrocfer** [comment]
For anyone following this issue: a new discussion has been opened specifically about a possible community-maintained Helm chart: https://github.com/opencve/opencve/issues/732.

We’ll continue the conversation there to keep things focused and easier to follow.
