### ISSUE TITLE
Vendor search sometimes incorrectly returns no results 

### ISSUE THREAD

**Issue by nh2** [opencve/opencve#407]
https://app.opencve.io/vendors/?search=Git-scm shows `Vendors (0)` even though searching for `Git` lists a vendor `Git-scm` with that exact name (e.g. in https://app.opencve.io/vendors/?search=git&product_page=6&page=5).

That is contradictory and confusing.

One would expect exact search for a vendor to list that vendor.

## Screenshots (optional)

`Git-scm` vendor NOT found via `Git-scm`:

![image](https://github.com/user-attachments/assets/9e03c522-3380-4f23-ab13-8fab1e598113)

`Git-scm` vendor found via `Git`:

![image](https://github.com/user-attachments/assets/a65d6ef2-ad75-47ea-9203-bb798fad561f)

**Comment by ncrocfer** [comment]
Hello @nh2 ,

This is because the vendors & products search is case sensitive. But you're right, it make sense to swich it to case insensitive, so `Git-scm` for instance will return the wanted vendor.

A PR will follow, thank you for this feedback 👍

**Comment by nh2** [comment]
@ncrocfer I don't undersand. My search **was** case-exact, as the screenshots show.

**Comment by nh2** [comment]
> My search **was** case-exact, as the screenshots show.

Your fix to opencve.io did work, it now produces the desired results (though I still don't understand why it didn't work before, given that I entered case-exactly the name in the vendor table).

**Comment by ncrocfer** [comment]
It's because the name of the vendors and products in the table are [humanized](https://github.com/opencve/opencve/blob/v2/web/cves/templates/cves/vendor_list.html#L69) in Django template, and it [capitalizes](https://github.com/opencve/opencve/blob/v2/web/cves/utils.py#L80) the word.

But in DB it's just the raw data, in lowercase 😉
