### ISSUE TITLE
New email format is missing important information

### ISSUE THREAD

**Issue by neophiliac** [opencve/opencve#411]
## Expected Behavior
The old subject included the product that the CVE covered, for example
`1 alert on Ubuntu Linux`. That is useful because I'm not responsible for remediating CVEs for all products that I track so the label helped me to focus on my responsibilities before my curiosity.

Also, the body of the email was labeled with the product.

## Actual Behavior
The new subject is `[OpenCVEv1] 10 vulnerabilities found` with no product on the subject line or in the body of the email. I don't get that info until I click the link to get details about the CVE. The product is obvious for some CVEs, but not all and the risk of missing something important means I need to look at the details of almost every CVE in the email. I'm not going to guess at the increase in the load on your web servers but I'm confident that it is higher since the email subject change.

The last email I received with the old (useful) subject format was dated August 29 and the first one with the new subject format was received September 6th so the change must have been rolled out between those dates.

## Steps to Reproduce the Problem
- Look at an email's subject

## Specifications
  - Platform: email

**Comment by ncrocfer** [comment]
Hello,

Thank you for your detailed feedback!

You’re right, having more details in the subject is valuable. We’ve added your suggestion to our backlog for future improvements 👍  For information the change in the email format is a result of the release of OpenCVE v2, which went live last week.

> "That is useful because I'm not responsible for remediating CVEs for all products that I track so the label helped me to focus on my responsibilities before my curiosity"

I’d like to highlight a new feature in OpenCVE v2 that might be helpful for you. We’ve introduced the concept of **projects within organizations**. Now, subscriptions to vendors and products are organized within projects, allowing you to compartmentalize your subscriptions. You can create separate email notifications for each project and assign them to different people, making it easier to focus on your specific responsibilities.

**Comment by markpent** [comment]
just adding my 2c in the hope this get higher priority. The change is a major step backwards in usability.
I'm at the point that It's probably easier to self host and patch the local version than to continue having to open each report to know if its related to a product I use (I subscribe to some generic vendors like 'debian')

**Comment by ncrocfer** [comment]
For information the update has been deployed 1 month ago: https://github.com/opencve/opencve/commit/77db8701dd0753347bf8e912119db3b6616f0844#diff-de83f1e18083b06c5cb35bac28a5cab57c45a1fa4beea800e7f085495ab3187e

Now the title displays the summary, including the vendors / products.
