### ISSUE TITLE
Clarification for Usage & Billing for OpenCVE V2

### ISSUE THREAD

**Issue by ValentinGep** [opencve/opencve#412]
Hello,

I would like some clarification on the features provided.

**Example:** 

In the Starter offer you can have 3 projects, 3 notifications, 3 Users and 15 Subscriptions.

Is it 3 notifications for 1 project or is it 3 notifications for all the projects?

Is it 15 subscriptions per Project or 15 subscriptions to be dispatched for all the Projects?

![image](https://github.com/user-attachments/assets/c1e6c4bb-d7f9-46e1-a5f5-8866c4e906e7)

I really enjoyed V1.
Have a nice day.

**Comment by ncrocfer** [comment]
Hello,

Thank you for your question. However, discussions related to the SaaS version of OpenCVE (OpenCVE.io) are not handled through this GitHub repository, which is dedicated to the open-source software only.

For inquiries regarding our SaaS offers (Starter, Pro, etc.), please feel free to reach out to us directly at support@opencve.io. We’ll be happy to assist you with any questions you may have.

Best regards,
The OpenCVE Team
