### ISSUE TITLE
Add tag for v2 releases

### ISSUE THREAD

**Issue by RolphH** [opencve/opencve#419]
**Is your feature request related to a problem?**
No tags added for v2 releases

**Additional comment**
Hi, would it be possible to also add tags to the v2 branch/releases. At the moment, there is none and only a v2 branch. We would like to make use of tags to have more control over which version of OpenCVE we are running locally and prevent sudden updates.

Otherwise we would need to fork the project for now and use our forked repo to deploy OpenCVE.

**Comment by ncrocfer** [comment]
Hello,

The `v2` branch is still in Beta, but we'll do it once it will be merged in the production (`master`) branch.

**Comment by MoussaOudihat** [comment]
Hello is the V2 still in beta ?

Thank you

**Comment by burnziii** [comment]
Any news about v2 release?

**Comment by ncrocfer** [comment]
The v2 has been officially released: https://github.com/opencve/opencve/releases/tag/v2.0.0
