### ISSUE TITLE
Get CVE api pagination

### ISSUE THREAD

**Issue by emehd** [opencve/opencve#420]
## Expected Behavior
When calling the following URL, the next parameter of the JSON response should contain a link that redirects to page 2

## Actual Behavior
When calling the following URL: [OPENCVE Microsoft CVE ](https://app.opencve.io/api/cve/?cvss=critical&vendor=microsoft) , more than 4 results are returned and pagination provides a link for page 2, but the link in the next parameter of the JSON response is an HTTP link and not an HTTPS link. However, when the link is called, you are redirected to the OPENCVE homepage.

## Steps to Reproduce the Problem

  - call https://app.opencve.io/api/cve/?cvss=critical&vendor=microsoft
  - search for the next parameter
  - search for the next parameter and call up the link

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/8cd7f963-c390-4757-8dbb-602df973b39b)

**Comment by ncrocfer** [comment]
Oh good catch !
We'll check this issue, thank you for your feedback.
