### ISSUE TITLE
Bug: Graphviz (v2)

### ISSUE THREAD

**Issue by Matt-EPSI** [opencve/opencve#423]
## Expected Behavior
After running the setup process step by step, the command
 ./install.sh start-opencve-dag should finish the docker install.

## Actual Behavior
An error message is displayed :
"/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/dot_renderer.py: 28 UserWarning: COuld not import graphviz. Rendering graph to the graphical form at will not be possible."

Container states: 
- webserver : started
- redis : Healthy
- nginx : started
- postgres : healthy
- airflow-init : exited
- airflow-worker : running
- airflow-webserver : running
- airflow-scheduler : running

## Steps to Reproduce the Problem

  - Clone the repository : git clone -b v2 [repo address]
  - Run the install process step by step as indicated in the documentation
  - Issue should occur.

I managed to reproduce the issue 4 times on 4 new VMs (not snapshots).

## Specifications

  - OpenCVE version: v2
  - Python version: 3.11 (in container as it seems), 3.12.3 on the host
  - Platform: Ubuntu 24.04.1 LTS running on VSphere

**Comment by ncrocfer** [comment]
Hi,
Don't worry this is just a warning, the installation is still working :)

**Comment by Matt-EPSI** [comment]
Hi,
Thank you for your answer.

After your answer, I realized that I had not set the listening IP in the airflow config file. Issue solved !
