### ISSUE TITLE
Notifications Email / Webhook not working V2

### ISSUE THREAD

**Issue by PMX-Martijn** [opencve/opencve#424]
## Expected Behavior

i've installed V2 and configured mail and webhook notifications for every change to an CVE to see if it works but no notifications are received

## Actual Behavior

no notification received, not by mail and not with webhook

## Steps to Reproduce the Problem
Configure notifications for every possible change

## Specifications

  - OpenCVE version: C2
  - Python version:
  - Platform:

#############################

is there any way to troubleshoot this to see if an notification is being tried and it throws an error?

**Comment by ncrocfer** [comment]
The logs of the scheduler component can give you information about why you didn't receive a notification (maybe simply the changes didn't match any of your projects subscriptions).

Can you give us here some logs to dig into?

**Comment by ncrocfer** [comment]
This thread is being closed due to inactivity.
