### ISSUE TITLE
Issue API v1 for products PureStorage

### ISSUE THREAD

**Issue by eluich** [opencve/opencve#429]
Hi

I'm having trouble retrieving CVEs for PureStorage products purity//fa and purity//fb.

According to the /api/vendors/purestorage/products query, the product name is purity\ / \ /fa.

I've tried to encode the url with purity%5C%2F%5C%2Ffa but I get no response.

Do you have a solution?

**Comment by ncrocfer** [comment]
Hi,

Here is the URL with encoded parameters: https://app.opencve.io/api/cve/?vendor=purestorage&product=purity%5C/%5C/fa
