### ISSUE TITLE
`POSTGRES_` vars in Docker `.env` template not used

### ISSUE THREAD

**Issue by The-Judge** [opencve/opencve#432]
## Expected Behavior

The [docs for `docker/.env`](https://docs.opencve.io/deployment/#configuration) state, that one may change the `POSTGRES_PASSWORD` variable. But later in that file, the Postgres-URIs are hardcoded with `opencve` instead of utilizing these vars.

## Actual Behavior

Users who follow the advise from the docs to change the Postgres Password, end up with a broken instance.

## Steps to Reproduce the Problem

  - Execute `./install.sh prepare`
  - Change `POSTGRES_PASSWORD` in `docker/.env`
  - Execute `./install.sh start`
  - Embrace your broken deployment

## Specifications

  - OpenCVE version: Commit [e9d1e11](https://github.com/opencve/opencve/commit/e9d1e11f77287e39ee607e7dbfb39bc3e6433e5c)
  - Python version: Any
  - Platform: Any

**Comment by ldurnez** [comment]
Fix merged: https://github.com/opencve/opencve/pull/433
Thank you for the PR!
