### ISSUE TITLE
`.gitignore` has the wrong path for `opencve.conf.template`

### ISSUE THREAD

**Issue by The-Judge** [opencve/opencve#434]
## Expected Behavior

`.gitignore` contains a rule, trying to ignore the file `opencve.conf.template` created by `install.sh`'s `add-config-files`-step.
So, no change should be shown in `git status` after triggering this step.

## Actual Behavior

Since `add-config-files` creates the file at `docker/conf/opencve.conf.template` but `.gitignore` contains a different path (`docker/config/opencve.conf.template`), this does not work as intended.

## Steps to Reproduce the Problem

  - execute `./install.sh prepare` or `./install.sh add-config-files`
  - execute `git status`
  - see git shows file `docker/conf/opencve.conf.template` as added/changed

## Specifications

  - OpenCVE version: commit [e9d1e11](https://github.com/opencve/opencve/commit/e9d1e11f77287e39ee607e7dbfb39bc3e6433e5c)
  - Python version: Any
  - Platform: Any

**Comment by ldurnez** [comment]
Fix merged: https://github.com/opencve/opencve/pull/435
Thank you for the PR!
