### ISSUE TITLE
proxy doesn't forward to webserver for localhost

### ISSUE THREAD

**Issue by nathan-atwork** [opencve/opencve#439]
## Expected Behavior
contacting `localhost:80` opens opencve UI

## Actual Behavior
contacting `localhost:80` defaults to nginx default page

## Steps to Reproduce the Problem

  - clone [opencve](https://github.com/opencve/opencve.git) locally
  - run installation script : `./install.sh`
  - on opencve host, contact `localhost:80`

## Specifications

  - OpenCVE version: v2 (commit bdc46d3)
  - Python version: Python 3.12.7
  - Platform: linux/docker

### expected
![image](https://github.com/user-attachments/assets/1947a2e2-6e0d-42c2-a921-d6309211da60)

### actual
![image](https://github.com/user-attachments/assets/4eee9e68-2fd6-4cbc-b4dc-0b7d7f860c7f)

**Comment by YoannPa** [comment]
Yes that's actually the problem I got. I'll just wait for the fix, and try again installing the docker later.

**Comment by nathan-atwork** [comment]
@YoannPa, please see suggested fix #441 for immediate resolution.

**Comment by YoannPa** [comment]
@nathan-atwork So I should just remove the entire content of /etc/nginx/conf.d/default.conf ?

**Comment by ldurnez** [comment]
Fix merged: #441
Thank you for your PR!

**Comment by nathan-atwork** [comment]
You're welcome :)

By the way, congratulations on the successful release of the V2. Thank you for your hard work and dedication to keep CVEs accessible for all !
