### ISSUE TITLE
server: Connection refused

### ISSUE THREAD

**Issue by hsninbil** [opencve/opencve#44]
Hi guys,
please i want to help me.
When i run the command (# opencve upgrade-db. ) here is the error message displayed ( Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?)
i allow all ports in firewall.
Thank you

**Comment by JMousqueton** [comment]
Hi, 

Did you install postgreSQL ?  if yes is the daemon running ?

**Comment by hsninbil** [comment]
Hi,
Yes
and the message now is 👍     
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "user"
FATAL:  password authentication failed for user "user"

(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by ncrocfer** [comment]
Not linked to OpenCVE, you need to read a Postgresql tutorial. If you can't we advise you to use online instance (https://www.opencve.io).

1. start PG instance
2. configure it (create db, create user...)
3. change database_uri field in your opencve.cfg file

PostgreSQL configuration (as well as Redis, or even the server configuration) is out of our scope support.
