### ISSUE TITLE
Http[s] for new V2 OpenCVE

### ISSUE THREAD

**Issue by cjmieny** [opencve/opencve#444]
Hi team, thank you for the awesome project you are running. 
I wanted to ask if there is a way to enable http[s] on the web portal?

**Comment by ldurnez** [comment]
Hello,

Thank you for your kind words!

Yes you can enable https on the Nginx service that will handle the SSL endpoint, however you need to use an external tool like certbot to generate your SSL certifcate and its renewing.

The Nginx docker with OpenCVE docker-compose file is the official image of [nginx](https://hub.docker.com/_/nginx) so you can apply the configuration changes for https following public documentations without issue.
