### ISSUE TITLE
SMTP Configuration

### ISSUE THREAD

**Issue by krismas** [opencve/opencve#449]
Hello,
I'm using OpenCVE v2 with Docker. In this configuration, how do I configure my SMTP server for notifications, user registration, password reset...?

**Comment by cjmieny** [comment]
I am currently experiencing an issue when creating new user: Server Error (500)

**Comment by CloudTheWolf** [comment]
From the location of the docker-compose.yml go to `../web/opencve/conf/setting.py`
Here you can set your SMTP as follows:

```
# Email Backend
EMAIL_BACKEND = "django.core.mail.backends.EmailBackend"

EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = "587"
EMAIL_HOST_USER = "apikey"
# SMTP Password (Or API Key if using Sendgrid)
EMAIL_HOST_PASSWORD = "SG.############"
EMAIL_USE_TLS = True
EMAIL_SUBJECT_PREFIX = "[OpenCVE]"

DEFAULT_FROM_EMAIL = "OpenCVE Alerts <opencve.mysite.com>"
```

**Comment by ncrocfer** [comment]
I confirm what @CloudTheWolf said, here is the documentation: https://docs.opencve.io/deployment/#configuration

**Comment by krismas** [comment]
Thank you very much for these informations. I had missed this documentation!
