### ISSUE TITLE
upgrade db of cves

### ISSUE THREAD

**Issue by mhsinj0** [opencve/opencve#450]
hi i install the platform before 2 wekkes and the cves don't updated 
i try these commands
sudo docker exec -it webserver opencve upgrade-db
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

sudo docker exec -it webserver opencve upgrade-db
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.

and this command take a long time to update 
sudo docker exec -it webserver opencve migrate-nvd
This command will migrate all existing CVEs into the new NVD format. Do you want to continue ? [y/N]: y
[*] Fetching https://services.nvd.nist.gov/rest/json/cves/2.0?startIndex=0
[*] Fetching https://services.nvd.nist.gov/rest/json/cves/2.0?startIndex=2000

there is way to update cve from specaficce date like from 2024/10/01 to 2024/11/11

**Comment by ncrocfer** [comment]
Hello,

Without additional logs it's not practical to help you :wink:

Anyway you're using the `v1` version, we invite you to switch to the `v2` one for more features. You can follow this documentation to install the new OpenCVE version: https://docs.opencve.io/deployment/
