### ISSUE TITLE
v2 Migration

### ISSUE THREAD

**Issue by Nautilus34** [opencve/opencve#459]
Hello,

Thank you for your work.

I can't find the documentation to update from docker version 1.5 to version 2.
Can you explain to me how to do it?

Thank you very much.

**Comment by ncrocfer** [comment]
Hello @Nautilus34 ,

Thank you very much for your kind words!

You’re correct that we currently lack migration documentation for updating from version 1.5 to version 2. We’ll be working on this shortly and will provide it as soon as it’s ready.

Thank you again for your patience and support!

**Comment by ncrocfer** [comment]
The documentation can be found here: https://docs.opencve.io/guides/migrate_opencve_v1/
