### ISSUE TITLE
airflow-init container failing to start

### ISSUE THREAD

**Issue by vasqueeg** [opencve/opencve#465]
## Expected Behavior
- All containers under OpenCVEV2 should start with no issues.

## Actual Behavior
- Getting an error below and resulted to fail to start the `airflow-init`

```
ERROR! Maximum number of retries (20) reached.

Last check result:
$ airflow db check
[2024-11-22T08:45:02.046+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres15" to address: Temporary failure in name resolution
...
...
...
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres15" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
Note: I've changed the postgres hostname into `postgres15` as I've also OpenCVE 1.5 installed on the same server (via docker compose) to make sure that it will not conflict on the OpenCVE 1.5.

## Steps to Reproduce the Problem

Note: I also have OpenCVE 1.5 build under docker compose on the same server.  With this, I need to alter the docker-compose.yaml file in order to prevent on container name conflict, binding ports etc.  As for the credentials, I used the default.

## Specifications

  - OpenCVE version: 2
  - Python version: Python 2.7.5
  - Platform: RHEL 7.9

## Screenshots (optional)

**Comment by vasqueeg** [comment]
Hello - Just a gentle follow-up on this.  Let me know if further information needed.  Thank you!

**Comment by ncrocfer** [comment]
Hello @vasqueeg ,

The error you’re encountering indicates an issue with your Docker Compose configuration. Specifically, the postgres15 container doesn’t seem to be reachable by SQLAlchemy.

Please note that you cannot directly connect an OpenCVE v1 database to an OpenCVE v2 web instance. The database schemas are entirely different, and a migration process is required to move data from v1 to v2.

To resolve this issue, I recommend the following steps:

- use the standard Docker Compose configuration without any custom modifications. This ensures compatibility and allows us to better support you if further issues arise: https://docs.opencve.io/deployment/
- then follow the official migration guide to properly transition your data from OpenCVE v1 to OpenCVE v2: https://docs.opencve.io/guides/migrate_opencve_v1/

**Comment by vasqueeg** [comment]
Thanks @ncrocfer for the feedback.  I've ended up by building the OpenCVEv2 on another server.  So far, it is working properly.  

I have a question though if you don't mind.  In the docker-compose.yaml file, the volumes are defined as below:

```
volumes:
    postgres-db:
    staticfiles:
    repositories:
``` 

Wherein the volumes consumed the space in the `/var/lib/docker/volumes` of my server.  I attempted to change the volumes to be persistent by putting the following:

```
volumes:
    postgres-db:/data/opencve/postgres-db
    staticfiles:
    repositories:/data/opencve/repositories
```

But I'm getting an error on starting the stack.  Any advise on how I can move the `postgres-db` and `repositories` to my desired partition so it will be more easier to me to manage the disk partition(s) on my server?

Thank you in advance!

**Comment by christer74** [comment]
I bump this issue, got the same behavior. I'm somewhat fresh to docker/git, so bare with me. :)

A first time v2 install works fine. My issue arises on subsequent git pulls. 
Procedure I've used is: stop and remove containers, git pull + /install.se start.
Results in a working OpenCVE as expected, even over time (say days)  but the airflow-init container exits (in green fashion) during the ./install.sh start.

**Comment by ncrocfer** [comment]
I close this issue as the original issue was fixed. Please open new ones if needed.
