### ISSUE TITLE
Usage of dashboard tags in V2, pending implementation + documentation or bug?

### ISSUE THREAD

**Issue by christer74** [opencve/opencve#468]
## Expected Behavior
Some sort of filtering function?
Documentation on usage is ot easy available, maybe the implementation is pending?

## Actual Behavior
Response when selecting a tag and searching results in:
Web error, the resource is not found on this server, ie nothing.

## Steps to Reproduce the Problem
Creation of a tag.
In dashboard views where tag can be used, pick it, hit search button -> results in above web error.

## Specifications

  - OpenCVE version: Latest git pull as of 2024-11-26
  - Python version: Latest git pull as of 2024-11-26
  - Platform: Debian 12, Docker.

**Comment by 1sbruce** [comment]
I have the same issue both from the latest pull - 04/12/2024 and also the same behaviour on the web version of the app.
Are tags simply not working yet in V2?

![tag](https://github.com/user-attachments/assets/1f0fe31b-fe83-4f14-8c1a-6954ced9ba3b)

**Comment by ncrocfer** [comment]
> Are tags simply not working yet in V2?

@1sbruce No, tag search works fine:

<img width="966" alt="image" src="https://github.com/user-attachments/assets/0445e6b0-ff11-467a-90b2-8f692bf12edb">

@christer74 We can add a guide about how to use tag indeed, but in fact the concept is pretty simple:

- you go on your settings: https://app.opencve.io/settings/tags/

- you go on a CVE and click on the edit icon in the Tags panel
<img width="338" alt="image" src="https://github.com/user-attachments/assets/fa2d7561-b548-47be-a21a-e61066508d0a">


- then you attach the wanted tag to the CVE
<img width="657" alt="image" src="https://github.com/user-attachments/assets/fd4fe583-7586-4c18-b526-8dc72b6002bc">

@christer74 what's the name of your tag? Does it contain a special character?

**Comment by 1sbruce** [comment]
Thanks for taking the time to respond @ncrocfer 

I have been using the process you show above and I have no problem creating or attaching tags to CVEs, its just that the search returns a "Resource not found" response which seems to be the same issue that @christer74 is having.

In the below I have created a simple tag.

Title: Test
Description: Test
Attached to multiple CVEs

<img width="590" alt="Attached_Tag" src="https://github.com/user-attachments/assets/ea340831-fef1-49bb-99e9-54ce461a27bb">

Select the tag as a search field in "Vulnerabilites" menu
<img width="581" alt="search" src="https://github.com/user-attachments/assets/fe63dd18-7b05-4407-ba7d-c31d5060af46">

Click "search" and get the below result
<img width="450" alt="error" src="https://github.com/user-attachments/assets/d0f70657-fdf3-4ed5-b05c-dbdbb465ee7c">

This example is using https://app.opencve.io/cve but I get the same using the downloaded docker version too.

**Comment by ncrocfer** [comment]
Ok, thanks to your help I found the bug! It will be fixed soon 😉

**Comment by christer74** [comment]
Thanx for adressing the issue, and yes, my issue report is covered by above scenario.
Keep the good work up!

**Comment by 1sbruce** [comment]
Many Thanks.
Appreciate your hard work on this project

**Comment by ncrocfer** [comment]
@christer74 @1sbruce The bug is now fixed, thanks for your feedbacks 😉
