### ISSUE TITLE
Email Notifications not Working

### ISSUE THREAD

**Issue by shnsys** [opencve/opencve#473]
## Expected Behavior
Email notifications in OpenCVE platform is not working as expected. However, the password reset option works without any issues

## Actual Behavior
Not receiving any email notification for any subscribed vendors/products. When checking the logs on Airflow can see the below error message which is causing this issue.

[2024-12-04, 08:00:13 AEST] {notifiers.py:268} INFO - Sending email notification to email@something.com (3 changes)
[2024-12-04, 08:00:14 AEST] {notifiers.py:323} ERROR - SMTPException(email@something.com): Error connecting to smtp.office365.com on port 587: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
[2024-12-04, 08:00:14 AEST] {python.py:202} INFO - Done. Returned value was: True
[2024-12-04, 08:00:14 AEST] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=***, task_id=notifications.send_notifications, map_index=0, execution_date=20241203T210000, start_date=20241203T220013, end_date=20241203T220014_

The SMTP has been configured as below.

- airflow.cfg
# The SMTP server used to send the email notifications
notification_smtp_host = smtp.office365.com
notification_smtp_user = email@something.com
notification_smtp_password = ***************
notification_smtp_mail_from = email@something.com
notification_smtp_port = 587
notification_smtp_use_tls = True
notification_smtp_validate_certs = True
notification_smtp_timeout = 30

- settings.py

# Email backend
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.office365.com"
EMAIL_HOST_USER = "email@something.com"
EMAIL_HOST_PASSWORD = "***************"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = "OpenCVE <email@something.com>"

I have tried disabling TLS on above config files and tried with port 25 but the issue persists. Since the password reset email comes through I can confirm there are no issues in Microsoft side, and we have enabled legacy authentication for this email account. 

## Specifications

  - OpenCVE version: V2
  - Python version:
  - Platform: Docker

**Comment by ncrocfer** [comment]
Hi @shnsys,

A quick search on Google led me to the following result: https://github.com/cole/aiosmtplib/issues/187.

It appears that `aiosmtplib` provides a `start_tls` option. While I’m not entirely certain about the outcome, you might want to test it on your OpenCVE instance. This would greatly help us during the debugging process, as I haven’t been able to reproduce the error on my end.

If this option resolves the issue, I will create a PR to implement the fix.

Looking forward to your feedback.

**Comment by shnsys** [comment]
Hi @ncrocfer,

Thank you for looking into this. As you suggested I made the changes to initiate start_tls and I can receive emails now.  The updated code is as follows. 

kwargs = {
    "hostname": conf.get("opencve", "notification_smtp_host"),
    "port": conf.getint("opencve", "notification_smtp_port"),
    "start_tls": conf.getboolean("opencve", "notification_smtp_use_tls"), 
    "validate_certs": conf.getboolean("opencve", "notification_smtp_validate_certs"),
    "timeout": conf.getint("opencve", "notification_smtp_timeout"),
}


However, I noticed that the hyper-links on the email does not show the valid IP address. 

![image](https://github.com/user-attachments/assets/f338cf56-ba31-47cd-8239-4c52a0360267)

I have already updated the web_base_url = <your_listening_ip or fqdn> pointing to my private IP address. (tried with both values http://192.168.x.x and 192.168.x.x). I am not sure if this is connected to the issue, I raised on https://github.com/opencve/opencve/issues/461

**Comment by shnsys** [comment]
Hi @ncrocfer,

I have managed to fix the above issue after rebooting the server. Appreciate if you can help to fix https://github.com/opencve/opencve/issues/461

**Comment by ncrocfer** [comment]
Great for `start_tls` option, I will add it in the code ! Checking for the other issue.

**Comment by ch3ikh** [comment]
> Hi @ncrocfer,
Hi,
Can you show me the path of the script or the conf file  that you changed please ?
Thanks a lot.
