### ISSUE TITLE
Fresh install from release sources don't start up.

### ISSUE THREAD

**Issue by itpalefox** [opencve/opencve#482]
## Expected Behavior
```
./install.sh start-docker-stack
--> Get PG ENV variables from docker compose env file
--> Starting Docker compose stack
[...]
--> Adding Airflow connections
[...]
--> Updating OpenCVE secret key
[...]
--> Restarting webserver
[...]
--> Collecting static files from Django webserver
[...]
```

## Actual Behavior
airflow-init don't finish and can't create containers:

> airflow-webserver
> airflow-worker
> airflow-schedule

airflow-init  docker logs is empty

## Steps to Reproduce the Problem

  - Download sources from [Releases](https://github.com/opencve/opencve/releases/tag/v2.0.0)
  - Unpack and go to docker folder
  - Run install.sh script

## Specifications

  - OpenCVE version: v2.0.0
  - Platform: Ubuntu 24.04 with Docker

## Screenshots (optional)
![Screenshot_NL_20241215_084629](https://github.com/user-attachments/assets/7f1c7ba1-3a49-4de4-a422-b4f0e2e124c2)

**Comment by ncrocfer** [comment]
Hi @itpalefox ,

Thanks for the feedback, we're checking that.

**Comment by itpalefox** [comment]
All installs like a charm when run command ./install.sh -r master
