### ISSUE TITLE
Opencve behind NPM

### ISSUE THREAD

**Issue by fastercz** [opencve/opencve#485]
Hello, I would like to start by thanking you for your great work. Unfortunately with the new version 2.0.0 the documentation is quite poor and I don't know what to do about it. Thank you for any help.

## Expected Behavior
Know which parameter and where to configure it. This is basic thing, it should be in docs.

## Actual Behavior
When i configure proxy host in my NginxProxyManager i get this: Forbidden (Origin checking failed - https://XXX.XXX.XXX does not match any trusted origins.)

## Steps to Reproduce the Problem
  - Install fresh OpenCve 2.0.0
  - Create Proxy host to port 80 on NPM
  - Try it

## Specifications

  - OpenCVE version: 2.0.0
  - Platform: Debian 12 + Docker 27.4.1

**Comment by ncrocfer** [comment]
Hi @fastercz,  

> Hello, I would like to start by thanking you for your great work  

Thank you for your kind feedback! 😊  

> When I configure a proxy host in my NginxProxyManager, I get this: Forbidden (Origin checking failed - https://xxx.xxx.xxx/ does not match any trusted origins.)  

As mentioned in the [documentation](https://docs.opencve.io/deployment/#configuration), the OpenCVE web component is based on Django:  

![Django-based component](https://github.com/user-attachments/assets/ebc6987d-91d2-4058-86bc-d06a78d30f4c)  

In your case, you may need to update the following Django settings:  

- **`ALLOWED_HOSTS`**: See the official documentation for details on how to configure it: https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts  
- **`CSRF_TRUSTED_ORIGINS`**: Refer to this documentation to adjust it: https://docs.djangoproject.com/en/5.1/ref/settings/#csrf-trusted-origins  

I think it will fixed your issue.

**Comment by fastercz** [comment]
Hello, this solved my problem. Thanks a lot :)

**Comment by ketsui-nc** [comment]
Maybe I could add some extra information for other people that would be in the same situation.

I got the same error while placing a reverse proxy in front of the opencve instance. I was able to acces to the webservice in https but when i tried to log myself i had the Forbidden (403) CSRF verification failed. Request aborted.

To fix it you need to go to opencve-2.1.0/web/opencve/conf/settings.py and add these lines

```
ALLOWED_HOSTS = ["your.domain.tld, "ip-if-you-need"]

# to allow django to accept CSRF token from the subdomain
CSRF_TRUSTED_ORIGINS = ["https://your.domain.tld"]

# to tell him hey you're behin a rp !
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# allow the secure
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

```

After that make sure to restart your dockers and you should be gucci, At least it worked for me after a lot of research XD

**Comment by avicoder** [comment]
I followed the above steps and added the lines in the settings.py file, but it still throwing the CSRF verification failed.

I am using docker compose to host it on a cloud, using cloudflare are the proxy server.

**Comment by avicoder** [comment]
This worked for me.

`opencve/web/opencve/conf/setting.py`

```
from opencve.conf.base import *  # noqa # pylint: disable=unused-import

CSRF_TRUSTED_ORIGINS = [
    "http://*.example.com",
    "https://cve.example.com"
]

```

**Comment by thomai** [comment]
Thanks for the quick response - makes sense for me.

I created a [pull request for the mentioned documentation change](https://github.com/opencve/opencve-docs/pull/46). However, I added a new section as this discussion is not about outgoing proxy servers but about reverse proxies.
