### ISSUE TITLE
Vendor list does not display

### ISSUE THREAD

**Issue by gacce** [opencve/opencve#5]
After successful setup, vendor list does not display on the app. (i followed the instructions to install the service)

**Comment by ncrocfer** [comment]
Can you be more precise ? (OS, Python version, only `vendors` table is empty or others too, etc.)

**Comment by gacce** [comment]
rhel8, python3. yes only vendors table

**Comment by ncrocfer** [comment]
Can you copy/paste your import logs ? It seems it's the same problem as this user : https://twitter.com/mcbazza/status/1344341987365941248

Not enought memory (XML file is really big).

**Comment by gacce** [comment]
Can you define system requirements please? im gonna try it again using more resources.

**Comment by ldurnez** [comment]
The main requirement is memory for the initial import, it can reach until 3.5G, so you can setup 4.5 or 5G to be safe compare to the OS you use. Afterwards, the worker use very small memory as only the diff is used with the NVD.

**Comment by gacce** [comment]
Thank you!
