### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by dugdug36** [opencve/opencve#52]
## Expected Behavior
I would like send notification to be sure smtp configuration works and I will receive CVE alerts.
## Actual Behavior
I correctly configured smtp in ssmtp.conf and ssmtp command works. 
My smtp dont need Login/password, but if I remove "smtp_username" and "smtp_password" in opencve.cfg
I have this message error : 
configparser.NoOptionError: No option 'smtp_username' in section: 'mail'
How to make check from opencve email notification feature ? And how to resolve this option error in my case ? 

## Steps to Reproduce the Problem
Try with Open SMTP without login password and without TLS. 
  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

**Comment by ldurnez** [comment]
Hello,

Can you try to let empty both variables like this:
`
; Configuration to set up SMTP mails.
smtp_server = <SERVER_IP_OR_NAME>
smtp_port = 25
smtp_use_tls = False
smtp_username =
stmp_password =
`

**Comment by dugdug36** [comment]
Hello @ldurnez,

Thanks for your reply, I dont have error anymore. But I still don't receive any email. 
How can I check configuration and force email notification ?. 
"ssmtp email@adress.com" works, so its should works with openCVE too.

**Comment by ldurnez** [comment]
Hello,

There is no email checker itself but when you register or you ask to reset your password, it will send you an email. So you can use this as a test.

**Comment by dugdug36** [comment]
Thanks @ldurnez, 

Its was very good idea, Its issue from celery, cuz i dont have any update since installation.
