### ISSUE TITLE
How to test Email alert feature

### ISSUE THREAD

**Issue by shuhaooo** [opencve/opencve#53]
Hello, I had set my smtp details, would like to ask are there any ways to test on the email alerting feature?
Thank you in advance.

**Comment by ncrocfer** [comment]
If you want to test your SMTP config you can just register a new user (it sends an email containing the confirmation link).

To receive alerting emails you need to subscribe to vendors and products, you will receive a mail as soon as an alert will be created for these vendors and products (meaning a CVE has been created or updated for them).

Without that no, there's no way to "manually" create an alert to try the email alerting feature.

**Comment by shuhaooo** [comment]
Hi ncrocfer, crystal clear. Thank you very much!
