### ISSUE TITLE
cve

### ISSUE THREAD

**Issue by trh812** [opencve/opencve#61]
## Steps to Reproduce the Problem

  - 
  - 
  - 

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

## Screenshots (optional)

Some cve cannot be searched out, and there are some gaps with the official website of cve

**Comment by ncrocfer** [comment]
Can you be more explicit and provide details ?

**Comment by ncrocfer** [comment]
Closed due to inactivity of requester.
