### ISSUE TITLE
unable to parse CPE list

### ISSUE THREAD

**Issue by JackyTsuuuy** [opencve/opencve#68]
tried few times ，but still can't parse cpe list
```
#####################
Importing CPE list...
#####################
[*] Downloading https://nvd.nist.gov/feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml.gz... (done in 13.315s).
[*] Parsing XML elements...Killed
```

**Comment by ncrocfer** [comment]
In requirements doc :

> During the import of initial data OpenCVE will download and parse huge files, like the CPE dictionnary. For that we recommend you 3.5G RAM at least.

You must have more RAM.

**Comment by mailprogerald** [comment]
Bonjour à tous,

je rencontre le même problème lors de l'import des CPE.
J'ai une VM avec 4go de RAM

Merci pour votre aide

**Comment by ncrocfer** [comment]
@mailprogerald En effet les 3.5G défini dans la doc sont à titre indicatif, si ta machine fait autre chose en même temps il te faudra évidemment plus de RAM ;)

**Comment by mailprogerald** [comment]
Merci pour ton retour.
Je réinstalle opencve sur un autre machine et te tiendrai au courant.
Cordialement 
Gérald

**Comment by mailprogerald** [comment]
Ça fonctionne
Merci
