### ISSUE TITLE
Unable to proxify OpenCVE as static assets are referenced with the whole URL

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#69]
## Expected Behavior
The header static assets get loaded either way the app is running behind a proxy.

## Actual Behavior
The application fulfills the headers with the whole URL.

## Steps to Reproduce the Problem

Configure Nginx on top of the opencve application.
## Specifications

  - OpenCVE version: 1.0.2
  - Python version: Python 3.9
  - Platform: Windows

## Screenshots (optional)
![2021-02-22 15_56_23-Window](https://user-images.githubusercontent.com/2176256/108725820-11ef4580-7527-11eb-8b1d-b913caed6c72.png)

**Comment by ldurnez** [comment]
Hello @Xumeiquer,

You can use Nginx in front of OpenCVE. You need to change the server_name variable in opencve.cfg for your fqdn and use proxy_pass in Nginx configuration, for instance:
proxy_pass         http://127.0.0.1:29000;

With https setup, you need to set this variable to True in opencve.cfg:
use_reverse_proxy = True

And in your Nginx configuration, add these 2 lines to let the application build https url:
proxy_set_header   X-Forwarded-Port 443;
proxy_set_header   X-Forwarded-Proto https;

**Comment by Xumeiquer** [comment]
Thanks, that fixed the issue.
