### ISSUE TITLE
Add tagging to CVE vulnerbilities and can filter based on tags

### ISSUE THREAD

**Issue by summershrimp** [opencve/opencve#77]
**Is your feature request related to a problem?**
Add tagging to CVE vulnerbilities and can filter based on tags

**Do you have a solution in mind, or a suggestion to improve OpenCVE?**
just like issues on github, we can add tags to issue and filter by tags

**Additional comment**
nope

**Comment by ncrocfer** [comment]
For info we're currently working on it, to let you filter, sort, prioritize yourself the list of CVE ;) We also want to let you easily search in this tag, with a small but useful DSL language (like in Github issues).

**Comment by summershrimp** [comment]
great

**Comment by ncrocfer** [comment]
Closed by #108
