### ISSUE TITLE
opencve webserver error

### ISSUE THREAD

**Issue by linsihao7788** [opencve/opencve#79]
## Expected Behavior
![226](https://user-images.githubusercontent.com/46431972/109920104-c42bc780-7cf4-11eb-857f-32ab8122b961.png)

## Steps to Reproduce the Problem
I changed the server_name = 10.224.100.6:8000 in the opencv.cfg file but could not access the 10.224.100.6:8000 access page

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform:

**Comment by ncrocfer** [comment]
The `server_name` setting is used for Flask itself, to generate the full links in emails for example.

If you want to change your binding you the `-b` option of Gunicorn (https://docs.gunicorn.org/en/20.1.0/run.html#commonly-used-arguments) : `opencve webserver -b x.x.x.x:1234`

**Comment by linsihao7788** [comment]
Hi.Could you please tell me what I should do if I want OpenCVE Celery Work-L Info and OpenCVE Celery Beat -L Info to run in the background and generate log files?

**Comment by ncrocfer** [comment]
This question is not related at all with your initial issue, and you didn't even reply to my answer. So I close this issue.

For you second question : `opencve celery worker -D -f /tmp/foo`.

Celery documentation is your friend for another question related to the worker and the beat.
