### ISSUE TITLE
Problems update (unique id)

### ISSUE THREAD

**Issue by naxonez** [opencve/opencve#84]
Hi,

Im having problems when opencve is triying to update the database with new CVEs. The error show that are some problems inserting a new value because the query is trying to create a vendors_name_key when it exists.

## Expected Behavior
Update database with new cves

## Actual Behavior
[ERROR/ForkPoolWorker-4] Task HANDLE_EVENTS[d1477d2b-c975-4bc6-b92e-5f6166aa452c] raised unexpected: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "vendors_name_key"\nDETAIL:  Key (name)=(strangerstudios) already exists.\n\n[SQL: INSERT INTO vendors (id, created_at, updated_at, name) VALUES (%(id)s, now(), now(), %(name)s)]\n[parameters: {\'id\': UUID(\'b8607d61-7f42-4e0e-b434-6c19fae8828e\'), \'name\': \'strangerstudios\'}]\n(Background on this error at: http://sqlalche.me/e/gkpj)',)

## Steps to Reproduce the Problem
I had running opencve few days and now i have this problem when im trying to update

## Specifications

  - OpenCVE version: opencve, version 1.0.2
  - Python version: 3.6
  - Platform: Ubuntu 18.04

**Comment by ncrocfer** [comment]
We run several instances of OpenCVE and we never had this problem, nor we can reproduce it.

From what I can see the problem is a broken transaction, try to rollback it :

```
$ export FLASK_APP=opencve.app:app && flask shell
Python 3.6.2 (default, Dec  3 2020, 20:12:39)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
App: opencve [prod]
Instance: /Users/ncrocfer/Dev/opencve/instance
>>> from opencve.extensions import db
>>> db.session.rollback()
>>>
```
Not sure about the success of that because as I said we never encountered this error.

**Comment by naxonez** [comment]
Hi ncrocfer,

Thanks for you answer, using this command now seems that all run ok again.

Regards.
