### ISSUE TITLE
[feature request] inventory

### ISSUE THREAD

**Issue by dogasantos** [opencve/opencve#93]
Hi,
along with the previous feature request created by me, i'd like to add this one:

Create a simple inventory table and cross-refence with the CPE/CVE database.

It would be fantastic to have this tool as our (security team) inventory with basic info (ip, host, urls, ports/services, cpe strings) then make the "automatic" subscribe via cpe strings.

THAT would be a huge leap forward.
At the moment, I'm creating my own inventory and trying to make the calls via opencv via API (wich is not working due to auth bug and lack of api /cpe support)

thanks guys

**Comment by ncrocfer** [comment]
I'm not sure to understand your need, can you please give examples ? What kind of assets the inventory would contain ?

BTW you're talking about problems (`wich is not working due to auth bug and lack of api /cpe support`), what bug are you talking about ?
