### ISSUE TITLE
[feature_request] Add test email feature

### ISSUE THREAD

**Issue by zekicker** [opencve/opencve#94]
Hi,

It could be useful to add a feature to test email configuration to check if notifications are working well. 

Regards,

**Comment by ncrocfer** [comment]
Hi,
I'm not sure if it's the goal of OpenCVE to check your SMTP configuration... If you're not sure you can use the "forget password" feature, or the "register" one.

**Comment by zekicker** [comment]
Hi,

Understood, but since there is no logs with the docker install and an "Internal Server Error" with the "Forget password" and "Register" features, difficult to troubleshoot...

By the way, number of project have this feature to test this setting in the admin panel regarding the differents SMTP configurations.
