### ISSUE TITLE
SQLAlchemy authentication error

### ISSUE THREAD

**Issue by xme** [opencve/opencve#95]
## Expected Behavior

Deploy a Docker instance

## Actual Behavior

Can't populate data (SQLAlchemy error).
Postgresql password has been set in .env

## Steps to Reproduce the Problem

  - docker build
  - docker up
  - docker exec "import data"

Error is:
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "opencve"

## Specifications

Latest Docker build

**Comment by ncrocfer** [comment]
No answer from the initial author, I close this issue.
